window.translations = window.translations || {
    Español: {},
    Català: {},
    日本語: {}
};
Object.assign(window.translations.Español, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"En Matsuri siempre contamos con diferentes expositores de todo tipo para que puedas llevarte un recuerdo, encontrar algo exclusivo para ti, o hacer regalos a los tuyos, además puedes alquilar o comprar y vestir un yukata, comprar libros, artesanía tradicional japonesa, antigüedades, productos hechos a mano, obras de arte, y mucho más. Pronto podrás conocer a los expositores de este año, ¡estate atento a la web y nuestro instagram!",
    "If you have any questions, please contact us at":"Si tienes alguna duda, escríbenos a",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "¿Quiere ser expositor?",
    "Fill out the following form and we will contact you as soon as possible.":"Rellena el siguiente formulario y contactaremos contigo lo antes posible.",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"Política de organización y acceso",
    "Thank you for your interest in MATSURI Barcelona.":"Gracias por tu interés en MATSURI Barcelona.",
    "Below we explain our event policy and address the most common questions from visitors.":"A continuación explicamos los criterios de organización y las cuestiones más habituales entre los visitantes.",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona es un evento cultural privado y sin ánimo de lucro celebrado en Port Vell.",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"El coste del recinto (aprox. 40.000 €), junto con seguridad, escenario, electricidad e infraestructuras temporales, es imprescindible para garantizar la seguridad.",
    "Food and drinks":"Entrada de alimentos y bebidas",
    "In previous years, outside drinks caused operational issues.":"En años anteriores, el consumo de bebidas externas generó dificultades operativas.",
    "Therefore, in 2025 drinks were restricted, and in 2026":"Por ello, en 2025 se restringió su entrada y en 2026 se permitirá",
    "water will be allowed only":"únicamente agua",
    ", as a heat-prevention measure.":",como medida frente al calor.",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"Estas normas se basan en la legislación catalana y se detallan en las condiciones del ticket.",
    "Heat and dates":"Calor y fechas",
    "Event dates depend on official authorization.":"Las fechas dependen de autorización administrativa.",
    "In 2026, the festival will be held in":"En 2026 el evento se celebrará a",
    "mid-May":"mediados de mayo",
    ", to improve weather conditions.":", mejorando las condiciones climáticas.",
    "Admission fee":"Entrada de pago",
    "From 2013 to 2024 the event was free of charge.":"De 2013 a 2024 el acceso fue gratuito",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":", pero el aumento de costes obligó a introducir entrada en 2025.",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"El precio se mantiene entre los más bajos del sector y los menores de 12 años acceden gratis.",
    "Thank you for your understanding and continued support.":"Agradecemos su comprensión y apoyo.",
    "+info":"+info",
    // VENDEDORES
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "0":"",
    "read more": "leer más",
    //ARTISTAS
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"Mitsuru Nagata, es un artista japonés dedicado a la caligrafía Shodō y a la pintura Sumi-e. Realizará una demostración en el escenario y tendrá un puesto con sus obras originales. Tiene maestría en caligrafía por la escuela Futaba Shodō Kai y ha participado en diversos eventos en España, Japón y otros países. Participa en el Matsuri desdel año 2015.",
    "":"",
});
Object.assign(window.translations.Català, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"A Matsuri sempre comptem amb diferents expositors de tot tipus perquè puguis endur-te un record, trobar alguna cosa exclusiva per a tu o fer regals als teus. A més, pots llogar o comprar i vestir un yukata, comprar llibres, artesania tradicional japonesa, antiguitats, productes fets a mà, obres d’art i molt més. Aviat podràs conèixer els expositors d’aquest any, així que estigues atent a la web i al nostre Instagram!",
    "If you have any questions, please contact us at":"Si tens algun dubte, escriu-nos a",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "Vol ser expositor?",
    "Fill out the following form and we will contact you as soon as possible.":"Omple el següent formulari i ens posarem en contacte amb tu tan aviat com sigui possible.",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"Política d’organització i accés",
    "Thank you for your interest in MATSURI Barcelona.":"Gràcies pel teu interès en MATSURI Barcelona.",
    "Below we explain our event policy and address the most common questions from visitors.":"A continuació expliquem els criteris d’organització i els punts més consultats pels visitants.",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona és un esdeveniment cultural privat i sense ànim de lucre celebrat al Port Vell.",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"El cost d’ús del recinte (aprox. 40.000 €), juntament amb seguretat, escenari, electricitat i infraestructures temporals, és necessari per garantir un entorn segur.",
    "Food and drinks":"Entrada de menjar i begudes",
    "In previous years, outside drinks caused operational issues.":"El consum de begudes externes ha generat problemes operatius en el passat.",
    "Therefore, in 2025 drinks were restricted, and in 2026":"Per aquest motiu, el 2025 es va restringir l’entrada de begudes, però el 2026 es permetrà",
    "water will be allowed only":"l’entrada d’aigua",
    ", as a heat-prevention measure.":", com a mesura contra la calor.",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"Les normes segueixen la regulació catalana i consten a les condicions del tiquet.",
    "Heat and dates":"Gestió de la calor",
    "Event dates depend on official authorization.":"Les dates depenen de l’autorització administrativa.",
    "In 2026, the festival will be held in":"El 2026 l’esdeveniment se celebrarà a",
    "mid-May":"mitjans de maig",
    ", to improve weather conditions.":",millorant les condicions climàtiques.",
    "Admission fee":"Entrada de pagament",
    "From 2013 to 2024 the event was free of charge.":"Entre 2013 i 2024 l’accés va ser gratuït.",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":"L’augment de costos va fer necessari introduir entrada el 2025.",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"El preu és dels més baixos entre esdeveniments similars i els menors de 12 anys entren gratuïtament.",
    "Thank you for your understanding and continued support.":"Gràcies per la vostra comprensió i suport continuat.",
    "+info":"+info",
    // VENDEDORES
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "0":"",
    "read more": "llegir més",
    //ARTIS"read more":"",TAS
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"Mitsuru Nagata, és un artista japonès dedicat a la cal·ligrafia Shodō i a la pintura Sumi-e.  Realitzarà una demostració a l'escenari i tindrà un lloc amb les obres originals.  Té mestratge en cal·ligrafia per l'escola Futaba Shodō Kai i ha participat en diversos esdeveniments a Espanya, Japó i altres països.  Participa al Matsuri des de l'any 2015.",
    "":"",
});
Object.assign(window.translations.日本語, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"マツリでは、さまざまな出展者が揃っており、お土産を持ち帰ったり、自分だけの特別なものを見つけたり、大切な人へのギフトを選んだりすることができます。また、浴衣をレンタルまたは購入して着ることもでき、本、伝統的な日本の工芸品、骨董品、手作りの作品、アート作品なども購入可能です。今年の出展者たちもまもなくご紹介予定ですので、ぜひウェブサイトやInstagramをチェックしてください！",
    "If you have any questions, please contact us at":"ご不明な点がございましたら、ご連絡ください：",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "出展者になりませんか？",
    "Fill out the following form and we will contact you as soon as possible.":"以下のフォームにご記入ください。できるだけ早くご連絡いたします。",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"運営方針および入場に関するご説明",
    "Thank you for your interest in MATSURI Barcelona.":"このたびはMATSURI Barcelona に関心をお寄せいただき、ありがとうございます。",
    "Below we explain our event policy and address the most common questions from visitors.":"本ページでは、来場者の皆さまから多く寄せられているご質問を踏まえ、イベント運営の方針と事実関係をご説明します。",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona は、Port Vell を会場とする民間主催の非営利文化イベントです。",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"会場使用料（約40,000ユーロ）に加え、ステージ、電気、警備、仮設設備（テーブル・椅子・パラソル等）など、来場者の安全とイベント環境を維持するための運営費が発生しています。",
    "Food and drinks":"飲食物の持ち込みについて",
    "In previous years, outside drinks caused operational issues.":"過去には外部から持ち込まれた飲食物（アルコール含む）の会場内消費が多く、清掃・安全・運営面に大きな影響がありました。",
    "Therefore, in 2025 drinks were restricted, and in 2026":"そのため2025年まではドリンク全般の持ち込みを制限しましたが、2026年は",
    "water will be allowed only":"水に限り持ち込みを許可します。",
    ", as a heat-prevention measure.":"熱中症対策としてです。",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"これらのルールはカタルーニャ州の規定に基づき、チケット購入時の規約に明記されています。",
    "Heat and dates":"暑さへの対応",
    "Event dates depend on official authorization.":"開催日は毎年、主催者の希望をもとに申請しますが、最終的な決定は管轄機関による許可制です。",
    "In 2026, the festival will be held in":"2026年は開催時期を",
    "mid-May":"5月中旬とし",
    ", to improve weather conditions.":"、気候条件の改善を図ります。",
    "Admission fee":"入場料について",
    "From 2013 to 2024 the event was free of charge.":"本イベントは2013年から2024年まで10回にわたり無料開催を続けてきましたが、運営コストの増加により、2025年から入場料を導入しました。",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":"同規模の民間イベントと比較しても最低水準の料金に抑え、12歳以下は無料としています。",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"2025年は来場者数が減少しましたが、安全性や体験の質が向上したという評価が多く寄せられています。",
    "Thank you for your understanding and continued support.":"MATSURI Barcelona は、日本文化を伝える場として、現実的に継続可能な形を模索しています。ご理解とご協力を心よりお願い申し上げます。",
    "+info":"＋詳細",
    // VENDEDORES
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "0":"",
    "read more": "続きを読む",
    //ARTIS"read more":"",TAS
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"長田充（ながた みつる）、書道・墨絵アーティスト。双葉書道会で書道の師範資格を取得し、スペインや日本をはじめ、世界各国のさまざまなイベントで幅広く活躍。Matsuriには2015年より参加。ステージでのデモンストレーションを行うとともに、オリジナル作品を展示・販売するブースを出店。",
    "":"",
});