window.translations = window.translations || {
    Español: {},
    Català: {},
    日本語: {}
};
Object.assign(window.translations.Español, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"En Matsuri siempre contamos con diferentes expositores de todo tipo para que puedas llevarte un recuerdo, encontrar algo exclusivo para ti, o hacer regalos a los tuyos, además puedes alquilar o comprar y vestir un yukata, comprar libros, artesanía tradicional japonesa, antigüedades, productos hechos a mano, obras de arte, y mucho más. Pronto podrás conocer a los expositores de este año, ¡estate atento a la web y nuestro instagram!",
    "If you have any questions, please contact us at":"Si tienes alguna duda, escríbenos a",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "¿Quiere ser expositor?",
    "Fill out the following form and we will contact you as soon as possible.":"Rellena el siguiente formulario y contactaremos contigo lo antes posible.",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"Política de organización y acceso",
    "Thank you for your interest in MATSURI Barcelona.":"Gracias por tu interés en MATSURI Barcelona.",
    "Below we explain our event policy and address the most common questions from visitors.":"A continuación explicamos los criterios de organización y las cuestiones más habituales entre los visitantes.",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona es un evento cultural privado y sin ánimo de lucro celebrado en Port Vell.",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"El coste del recinto (aprox. 40.000 €), junto con seguridad, escenario, electricidad e infraestructuras temporales, es imprescindible para garantizar la seguridad.",
    "Food and drinks":"Entrada de alimentos y bebidas",
    "In previous years, outside drinks caused operational issues.":"En años anteriores, el consumo de bebidas externas generó dificultades operativas.",
    "Therefore, in 2025 drinks were restricted, and in 2026":"Por ello, en 2025 se restringió su entrada y en 2026 se permitirá",
    "water will be allowed only":"únicamente agua",
    ", as a heat-prevention measure.":",como medida frente al calor.",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"Estas normas se basan en la legislación catalana y se detallan en las condiciones del ticket.",
    "Heat and dates":"Calor y fechas",
    "Event dates depend on official authorization.":"Las fechas dependen de autorización administrativa.",
    "In 2026, the festival will be held in":"En 2026 el evento se celebrará a",
    "mid-May":"mediados de mayo",
    ", to improve weather conditions.":", mejorando las condiciones climáticas.",
    "Admission fee":"Entrada de pago",
    "From 2013 to 2024 the event was free of charge.":"De 2013 a 2024 el acceso fue gratuito",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":", pero el aumento de costes obligó a introducir entrada en 2025.",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"El precio se mantiene entre los más bajos del sector y los menores de 12 años acceden gratis.",
    "Thank you for your understanding and continued support.":"Agradecemos su comprensión y apoyo.",
    "+info":"+info",
    // VENDEDORES ES
    "Online shop for traditional Japanese products: Daruma, Japanese fabrics, tote bags, kanzashi, koinobori, okiagari, and ceramics.":"Tienda online de productos tradicionales japoneses, Daruma, tela japonesa, totebag, kanzashis, koinoboris, okiagaris, cerámica.",
    "Independent publisher specializing in Japanese manga and artbooks. We publish titles of high artistic quality and for all tastes.":"Editorial independiente especializada en manga y artbooks japoneses. Publicamos títulos de gran calidad artística y para todos los gustos.",
    "Japanese‑inspired fashion infused with the designer’s family heritage and deep personal bond with Japanese culture.":"Ropa de inspiración japonesa basada en las raíces familiares y el vínculo personal con la cultura japonesa del diseñador.",
    "Among the great ships sailing across the vast ocean of the publishing market, Lapislàtzuli is an independent vessel — a small romantic sailboat that moves forward with the tenacity of the little ones, charting a beautiful course toward that safe harbor that is the reader’s bookshelf.":"Entre los grandes buques que navegan en este océano que es el mercado editorial, Lapislàtzuli es una embarcación independiente, una barquita de vela romántica que navega con la tenacidad de los pequeños, que surca las aguas en un viaje precioso hacia ese puerto seguro que es la estantería del lector.",
    'We are Teresa and Laura, mother and daughter, and we work with Japanese paper and fabric to create jewelry and accessories inspired by Japan. We make earrings, bracelets, rings, pendants, hairpins, keychains, and much more. All pieces are handmade and pass through both of our hands, which is why we say they are "jewelry made with four hands."':'Somos Teresa y Laura, madre e hija y trabajamos con papel y tela japonesa para elaborar joyas y complementos inspirados en Japón. Hacemos pendientes, pulseras, anillos, colgantes, pasadores para el pelo, llaveros y mucho más. Todas las piezas son artesanales y pasan por las manos de las dos, por eso decimos que son "joyas hechas a cuatro manos".',
    "Kimonos and charming Japanese souvenirs.":"Kimonos y recuerdos monos de Japón",
    "We create Mizuhiki accessories in Barcelona. Mizuhiki symbolizes respect and good fortune. Earrings, brooches… also perfect as a gift.":"Hacemos accesorios de Mizuhiki en Barcelona. Mizuhiki simboliza respeto y buena fortuna. Pendientes, broches… también perfecto para regalo.",
    "Made in Japan Shop offers vintage items from Showa period: restored flip clocks, sunglasses, watches, vinyl records, CDs, toys, comics and magazines.":"Made in Japan Shop ofrece artículos vintage del período Shōwa: relojes de sobremesa restaurados, gafas de sol, relojes, discos de vinilo, CDs, juguetes, cómics y revistas.",
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"Mitsuru Nagata, es un artista japonés dedicado a la caligrafía Shodō y a la pintura Sumi-e. Realizará una demostración en el escenario y tendrá un puesto con sus obras originales. Tiene maestría en caligrafía por la escuela Futaba Shodō Kai y ha participado en diversos eventos en España, Japón y otros países. Participa en el Matsuri desdel año 2015.",
    "I specialize in handcrafted resin hairpins. The designs are inspired by both traditional Asian styles and modern trends.":"Me dedico a la creación artesanal de horquillas con resina. Los diseños se inspiran tanto en los modelos tradicionales asiáticos como modernos.",
    "Unique kimonos, yukatas, and haoris, lovingly curated. Discover standout pieces and take home your own slice of Japan from the Matsuri.":"Kimonos, yukatas y haoris únicos, seleccionados con mimo. Descubre piezas especiales y llévate un pedacito de Japón en el Matsuri",
    "Since 2007, dedicated to importing goods from Japan and to selling tea.":"Desde 2007 dedicados a la importancia de mercancía desde Japón y a la venta de té",
    "At Omamori Costura, I transform accessories into talismans. A coin purse that brings you good luck, a bag that protects you, or a headband that makes you feel safe. In Japan, everything has meaning, which is why the fabrics I use are printed with designs full of power and protection.":"En Omamori Costura transforma complementos en amuletos. Un monedero que te trae la buena fortuna, un bolso que te protege o una diadema que te hace sentir segura. En Japón todo tiene un significado, por eso las telas que utilizo llevan estampados llenos de poder y protección.",
    "Seiwa Resin is handcrafted jewelry inspired by mono no aware: the beauty of the ephemeral, capturing nature in resin with minimalist elegance.":"Seiwa Resin es joyería artesanal inspirada en el mono no aware: la belleza de lo efímero, capturando naturaleza en resina con elegancia minimalista.",
    'I would like to introduce you to "The Tale of Setsuko", a journey through ancient and historical Japan told through artistic prints on Japanese paper. And, on the other hand, my new project "1,000 Ways to Wish for Peace" - a collection of Tote Bags and Book Sleeves with playful designs, where we ask animals how they would wish for Peace, imitating the strokes of Japanese calligraphy. Enjoy the journey… and see you along the way!':'Me gustaría presentaros "El Relato de Setsuko", un viaje por el Japón antiguo y del pasado relatado a través de láminas artísticas sobre papel japonés. Y, por otro lado, mi nuevo proyecto "1.000 formas de desear Paz", de Tote Bags y Fundas de Libro con diseños divertidos, donde le preguntamos a animales cómo desearían Paz imitando el pincel de caligrafía japonesa. Disfrutad del camino. ¡Y nos vemos en él!',
    "Handmade with authentic Japanese fabrics.":"Hecho a mano, con las telas japonesas.",
    "9":"",
    "0":"",
    "read more": "leer más",
    //ARTISTAS,
    "":"",
});
Object.assign(window.translations.Català, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"A Matsuri sempre comptem amb diferents expositors de tot tipus perquè puguis endur-te un record, trobar alguna cosa exclusiva per a tu o fer regals als teus. A més, pots llogar o comprar i vestir un yukata, comprar llibres, artesania tradicional japonesa, antiguitats, productes fets a mà, obres d’art i molt més. Aviat podràs conèixer els expositors d’aquest any, així que estigues atent a la web i al nostre Instagram!",
    "If you have any questions, please contact us at":"Si tens algun dubte, escriu-nos a",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "Vol ser expositor?",
    "Fill out the following form and we will contact you as soon as possible.":"Omple el següent formulari i ens posarem en contacte amb tu tan aviat com sigui possible.",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"Política d’organització i accés",
    "Thank you for your interest in MATSURI Barcelona.":"Gràcies pel teu interès en MATSURI Barcelona.",
    "Below we explain our event policy and address the most common questions from visitors.":"A continuació expliquem els criteris d’organització i els punts més consultats pels visitants.",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona és un esdeveniment cultural privat i sense ànim de lucre celebrat al Port Vell.",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"El cost d’ús del recinte (aprox. 40.000 €), juntament amb seguretat, escenari, electricitat i infraestructures temporals, és necessari per garantir un entorn segur.",
    "Food and drinks":"Entrada de menjar i begudes",
    "In previous years, outside drinks caused operational issues.":"El consum de begudes externes ha generat problemes operatius en el passat.",
    "Therefore, in 2025 drinks were restricted, and in 2026":"Per aquest motiu, el 2025 es va restringir l’entrada de begudes, però el 2026 es permetrà",
    "water will be allowed only":"l’entrada d’aigua",
    ", as a heat-prevention measure.":", com a mesura contra la calor.",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"Les normes segueixen la regulació catalana i consten a les condicions del tiquet.",
    "Heat and dates":"Gestió de la calor",
    "Event dates depend on official authorization.":"Les dates depenen de l’autorització administrativa.",
    "In 2026, the festival will be held in":"El 2026 l’esdeveniment se celebrarà a",
    "mid-May":"mitjans de maig",
    ", to improve weather conditions.":",millorant les condicions climàtiques.",
    "Admission fee":"Entrada de pagament",
    "From 2013 to 2024 the event was free of charge.":"Entre 2013 i 2024 l’accés va ser gratuït.",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":"L’augment de costos va fer necessari introduir entrada el 2025.",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"El preu és dels més baixos entre esdeveniments similars i els menors de 12 anys entren gratuïtament.",
    "Thank you for your understanding and continued support.":"Gràcies per la vostra comprensió i suport continuat.",
    "+info":"+info",
    // VENDEDORES CA
    "Online shop for traditional Japanese products: Daruma, Japanese fabrics, tote bags, kanzashi, koinobori, okiagari, and ceramics.":"Botiga en línia de productes tradicionals japonesos: Daruma, teixit japonès, totebags, kanzashis, koinoboris, okiagaris, ceràmica.",
    "Independent publisher specializing in Japanese manga and artbooks. We publish titles of high artistic quality and for all tastes.":"Editorial independent especialitzada en manga i artbooks japonesos. Publiquem títols de gran qualitat artística i per a tots els gustos.",
    "Japanese‑inspired fashion infused with the designer’s family heritage and deep personal bond with Japanese culture.":"Roba d’inspiració japonesa basada en les arrels familiars i el vincle personal amb la cultura japonesa del dissenyador.",
    "Among the great ships sailing across the vast ocean of the publishing market, Lapislàtzuli is an independent vessel — a small romantic sailboat that moves forward with the tenacity of the little ones, charting a beautiful course toward that safe harbor that is the reader’s bookshelf.":"Entre els grans vaixells que naveguen en aquest oceà que és el mercat editorial, Lapislàtzuli és una embarcació independent, una barqueta de vela romàntica que navega amb la tenacitat dels petits, que solca les aigües en un viatge preciós cap a aquell port segur que és la prestatgeria del lector.",
    'We are Teresa and Laura, mother and daughter, and we work with Japanese paper and fabric to create jewelry and accessories inspired by Japan. We make earrings, bracelets, rings, pendants, hairpins, keychains, and much more. All pieces are handmade and pass through both of our hands, which is why we say they are "jewelry made with four hands."':'Som la Teresa i la Laura, mare i filla, i treballem amb paper i tela japonesa per elaborar joies i complements inspirats en el Japó. Fem arracades, polseres, anells, penjolls, passadors per als cabells, clauers i molt més. Totes les peces són artesanals i passen per les mans de totes dues, per això diem que són "joies fetes a quatre mans".',
    "Kimonos and charming Japanese souvenirs.":"Quimonos i records bonics del Japó",
    "We create Mizuhiki accessories in Barcelona. Mizuhiki symbolizes respect and good fortune. Earrings, brooches… also perfect as a gift.":"Fem accessoris de Mizuhiki a Barcelona. El Mizuhiki simbolitza respecte i bona fortuna. Arracades, agulles… també perfectes per regalar.",
    "Made in Japan Shop offers vintage items from Showa period: restored flip clocks, sunglasses, watches, vinyl records, CDs, toys, comics and magazines.":"Made in Japan Shop ofereix articles vintage del període Shōwa: rellotges de solapa restaurats, ulleres de sol, rellotges, discos de vinil, CDs, joguines, còmics i revistes.",
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"Mitsuru Nagata, és un artista japonès dedicat a la cal·ligrafia Shodō i a la pintura Sumi-e.  Realitzarà una demostració a l'escenari i tindrà un lloc amb les obres originals.  Té mestratge en cal·ligrafia per l'escola Futaba Shodō Kai i ha participat en diversos esdeveniments a Espanya, Japó i altres països.  Participa al Matsuri des de l'any 2015.",
    "I specialize in handcrafted resin hairpins. The designs are inspired by both traditional Asian styles and modern trends.":"Em dedico a la creació artesanal de pinces i agulles de cabell amb resina. Els dissenys s’inspiren tant en els models tradicionals asiàtics com en els moderns.",
    "Unique kimonos, yukatas, and haoris, lovingly curated. Discover standout pieces and take home your own slice of Japan from the Matsuri.":"Quimonos, yukates i haoris únics, seleccionats amb cura. Descobreix peces especials i emporta’t un trosset del Japó al Matsuri",
    "Since 2007, dedicated to importing goods from Japan and to selling tea.":"Des de 2007, dedicats a la importància de la mercaderia des del Japó i a la venda de te.",
    "At Omamori Costura, I transform accessories into talismans. A coin purse that brings you good luck, a bag that protects you, or a headband that makes you feel safe. In Japan, everything has meaning, which is why the fabrics I use are printed with designs full of power and protection.":"A Omamori Costura transforma complements en amulets. Un moneder que et porta bona fortuna, una bossa que et protegeix o una diadema que et fa sentir segura. Al Japó tot té un significat, per això les teles que utilitzo porten estampats plens de poder i protecció.",
    "Seiwa Resin is handcrafted jewelry inspired by mono no aware: the beauty of the ephemeral, capturing nature in resin with minimalist elegance.":"Seiwa Resin és joieria artesanal inspirada en el mono no aware: la bellesa de l’efímer, capturant la natura en resina amb una elegància minimalista.",
    'I would like to introduce you to "The Tale of Setsuko", a journey through ancient and historical Japan told through artistic prints on Japanese paper. And, on the other hand, my new project "1,000 Ways to Wish for Peace" - a collection of Tote Bags and Book Sleeves with playful designs, where we ask animals how they would wish for Peace, imitating the strokes of Japanese calligraphy. Enjoy the journey… and see you along the way!':'M’agradaria presentar-vos "El Relat de Setsuko", un viatge pel Japó antic i del passat explicat a través de làmines artístiques sobre paper japonès. I, d’altra banda, el meu nou projecte ‘1.000 formes de desitjar Pau’, amb bosses de mà i i fundes de llibre amb dissenys divertits, on preguntem als animals com desitjarien la Pau imitant el pinzell de la cal·ligrafia japonesa. Gaudiu del camí... i ens hi veiem!',
    "Handmade with authentic Japanese fabrics.":"Fet a mà, amb teixits japonesos.",
    "9":"",
    "0":"",
    "read more": "llegir més",
    //ARTISTAS,
    "":"",
});
Object.assign(window.translations.日本語, {
    "At Matsuri, we always have a wide variety of exhibitors so you can take home a souvenir, find something unique for yourself, or buy gifts for your loved ones. You can also rent or buy and wear a yukata, purchase books, traditional Japanese crafts, antiques, handmade products, artwork, and much more. You'll soon be able to meet this year's exhibitors, so keep an eye on our website and Instagram!":"マツリでは、さまざまな出展者が揃っており、お土産を持ち帰ったり、自分だけの特別なものを見つけたり、大切な人へのギフトを選んだりすることができます。また、浴衣をレンタルまたは購入して着ることもでき、本、伝統的な日本の工芸品、骨董品、手作りの作品、アート作品なども購入可能です。今年の出展者たちもまもなくご紹介予定ですので、ぜひウェブサイトやInstagramをチェックしてください！",
    "If you have any questions, please contact us at":"ご不明な点がございましたら、ご連絡ください：",
    "stand@acjm.es":"stand@acjm.es",
    "Do you want to be an exhibitor?": "出展者になりませんか？",
    "Fill out the following form and we will contact you as soon as possible.":"以下のフォームにご記入ください。できるだけ早くご連絡いたします。",
    "MATSURI Barcelona":"MATSURI Barcelona",
    "Event policy and admission":"運営方針および入場に関するご説明",
    "Thank you for your interest in MATSURI Barcelona.":"このたびはMATSURI Barcelona に関心をお寄せいただき、ありがとうございます。",
    "Below we explain our event policy and address the most common questions from visitors.":"本ページでは、来場者の皆さまから多く寄せられているご質問を踏まえ、イベント運営の方針と事実関係をご説明します。",
    "MATSURI Barcelona is a private, non-profit cultural event held at Port Vell.":"MATSURI Barcelona は、Port Vell を会場とする民間主催の非営利文化イベントです。",
    "Venue fees (approx. €40,000), together with security, stage, electricity and temporary infrastructure, are essential to ensure a safe environment.":"会場使用料（約40,000ユーロ）に加え、ステージ、電気、警備、仮設設備（テーブル・椅子・パラソル等）など、来場者の安全とイベント環境を維持するための運営費が発生しています。",
    "Food and drinks":"飲食物の持ち込みについて",
    "In previous years, outside drinks caused operational issues.":"過去には外部から持ち込まれた飲食物（アルコール含む）の会場内消費が多く、清掃・安全・運営面に大きな影響がありました。",
    "Therefore, in 2025 drinks were restricted, and in 2026":"そのため2025年まではドリンク全般の持ち込みを制限しましたが、2026年は",
    "water will be allowed only":"水に限り持ち込みを許可します。",
    ", as a heat-prevention measure.":"熱中症対策としてです。",
    "These rules follow Catalan regulations and are stated in the ticket conditions.":"これらのルールはカタルーニャ州の規定に基づき、チケット購入時の規約に明記されています。",
    "Heat and dates":"暑さへの対応",
    "Event dates depend on official authorization.":"開催日は毎年、主催者の希望をもとに申請しますが、最終的な決定は管轄機関による許可制です。",
    "In 2026, the festival will be held in":"2026年は開催時期を",
    "mid-May":"5月中旬とし",
    ", to improve weather conditions.":"、気候条件の改善を図ります。",
    "Admission fee":"入場料について",
    "From 2013 to 2024 the event was free of charge.":"本イベントは2013年から2024年まで10回にわたり無料開催を続けてきましたが、運営コストの増加により、2025年から入場料を導入しました。",
    "Rising costs made this unsustainable, so admission was introduced in 2025.":"同規模の民間イベントと比較しても最低水準の料金に抑え、12歳以下は無料としています。",
    "Prices remain among the lowest for comparable events, and children under 12 enter free of charge.":"2025年は来場者数が減少しましたが、安全性や体験の質が向上したという評価が多く寄せられています。",
    "Thank you for your understanding and continued support.":"MATSURI Barcelona は、日本文化を伝える場として、現実的に継続可能な形を模索しています。ご理解とご協力を心よりお願い申し上げます。",
    "+info":"＋詳細",
    // VENDEDORES JP
    "Online shop for traditional Japanese products: Daruma, Japanese fabrics, tote bags, kanzashi, koinobori, okiagari, and ceramics.":"日本の伝統的な商品を扱うオンラインショップです。だるま、日本の布、トートバッグ、かんざし、こいのぼり、起き上がり小法師、陶器などを取り揃えています。",
    "Independent publisher specializing in Japanese manga and artbooks. We publish titles of high artistic quality and for all tastes.":"日本の漫画やアートブックを専門に扱う独立系出版社です。芸術性の高い作品を中心に、幅広いジャンルのタイトルをお届けしています。",
    "Japanese‑inspired fashion infused with the designer’s family heritage and deep personal bond with Japanese culture.":"デザイナー自身のルーツと、日本文化との個人的なつながりから生まれた、和のエッセンスを取り入れたファッションを展開しています。",
    "Among the great ships sailing across the vast ocean of the publishing market, Lapislàtzuli is an independent vessel — a small romantic sailboat that moves forward with the tenacity of the little ones, charting a beautiful course toward that safe harbor that is the reader’s bookshelf.":"広大な出版市場という大海原を航海する数多くの大型船のなかで、「Lapislàtzuli」は独立したの小さな一隻。ロマンあふれる帆船のように、小さき者ならではの粘り強さで進み続け、読者の本棚という安らぎの港を目指して、美しい航路を描いています。",
    'We are Teresa and Laura, mother and daughter, and we work with Japanese paper and fabric to create jewelry and accessories inspired by Japan. We make earrings, bracelets, rings, pendants, hairpins, keychains, and much more. All pieces are handmade and pass through both of our hands, which is why we say they are "jewelry made with four hands."':'私たちはテレサとラウラ、母と娘の二人組です。日本の紙や布を使い、日本にインスパイアされたジュエリーやアクセサリーを制作しています。ピアス、ブレスレット、リング、ネックレス、ヘアアクセサリー、キーホルダーなど、さまざまなアイテムを手がけています。すべての作品は手作りで、二人の手を通して仕上げているため、「四つの手で作るジュエリー」と呼んでいます。',
    "Kimonos and charming Japanese souvenirs.":"日本のかわいいお土産と着物。",
    "We create Mizuhiki accessories in Barcelona. Mizuhiki symbolizes respect and good fortune. Earrings, brooches… also perfect as a gift.":"バルセロナで水引アクセサリーを制作しています。水引は「敬意」と「幸運」を象徴しています。イヤリング、ブローチ…贈り物にもぴったりです。",
    "Made in Japan Shop offers vintage items from Showa period: restored flip clocks, sunglasses, watches, vinyl records, CDs, toys, comics and magazines.":"昭和時代のヴィンテージアイテムを取り扱っています。修復されたパタパタ時計、サングラス、腕時計、レコード、CD、おもちゃ、漫画、雑誌など。",
    "Mitsuru Nagata is a Japanese artist specializing in Shodō calligraphy and Sumi-e painting. He will give a demonstration on stage and have a stall displaying his original works. He holds a master's degree in calligraphy from the Futaba Shodō Kai school and has participated in various events in Spain, Japan, and other countries. He has been participating in the Matsuri since 2015.":"長田充（ながた みつる）、書道・墨絵アーティスト。双葉書道会で書道の師範資格を取得し、スペインや日本をはじめ、世界各国のさまざまなイベントで幅広く活躍。Matsuriには2015年より参加。ステージでのデモンストレーションを行うとともに、オリジナル作品を展示・販売するブースを出店。",
    "I specialize in handcrafted resin hairpins. The designs are inspired by both traditional Asian styles and modern trends.":"樹脂を用いたハンドメイドのヘアピンを制作しています。デザインは、アジアの伝統的な意匠から現代的なスタイルまで、幅広いインスピレーションをもとに生まれています。",
    "Unique kimonos, yukatas, and haoris, lovingly curated. Discover standout pieces and take home your own slice of Japan from the Matsuri.":"日本の着物や、かわいらしいお土産雑貨を取り揃えています。",
    "Since 2007, dedicated to importing goods from Japan and to selling tea.":"2007年より、日本からの商品の輸入とお茶の販売に取り組んでいます。",
    "At Omamori Costura, I transform accessories into talismans. A coin purse that brings you good luck, a bag that protects you, or a headband that makes you feel safe. In Japan, everything has meaning, which is why the fabrics I use are printed with designs full of power and protection.":"「Omamori Costura」では、身につける小物を“お守り”へと昇華させています。幸運を運ぶコインケース、あなたを守るバッグ、自信を与えてくれるヘアバンド。日本ではすべてのものに意味が宿るとされており、使用する生地には、力や守護の想いが込められた柄を選んでいます。",
    "Seiwa Resin is handcrafted jewelry inspired by mono no aware: the beauty of the ephemeral, capturing nature in resin with minimalist elegance.":"「Seiwa Resin」は、「もののあわれ」に着想を得たハンドメイドジュエリーブランドです。儚く移ろう美しさをテーマに、自然の一瞬を樹脂に閉じ込め、ミニマルで上品なデザインとして表現しています。",
    'I would like to introduce you to "The Tale of Setsuko", a journey through ancient and historical Japan told through artistic prints on Japanese paper. And, on the other hand, my new project "1,000 Ways to Wish for Peace" - a collection of Tote Bags and Book Sleeves with playful designs, where we ask animals how they would wish for Peace, imitating the strokes of Japanese calligraphy. Enjoy the journey… and see you along the way!':"「Setsuko Monogatari」は、日本の古き時代をテーマにしたアート作品シリーズです。和紙に描かれた作品を通して、日本の過去への旅をお楽しみいただけます。また、新プロジェクト『1,000通りの平和の願い』では、トートバッグやブックカバーに遊び心あふれるデザインを展開。動物たちが「平和」をどう願うのか、日本の書道の筆致を模して表現しています。",
    "Handmade with authentic Japanese fabrics.":"日本の生地で作った、ハンドメイド作品です。",
    "9":"",
    "0":"",
    "read more": "続きを読む",
    //ARTISTAS",
    "":"",
});