window.translations = window.translations || {
    Español: {},
    Català: {},
    日本語: {}
};
Object.assign(window.translations.Español, {
    "1. Introduction":"1. Introducción",
    "This Privacy Policy explains how this website (hereinafter referred to as “the Website”) collects, uses, and protects personal data, in accordance with Regulation (EU) 2016/679 of the European Parliament and of the Council (General Data Protection Regulation – GDPR), and applicable data protection laws.":"La presente Política de Privacidad explica cómo este sitio web (en adelante, el “Sitio Web”) recopila, utiliza y protege los datos personales, de conformidad con el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo (Reglamento General de Protección de Datos – RGPD) y la normativa aplicable en materia de protección de datos.",
    "By accessing and using this Website, users acknowledge that they have read and understood this Privacy Policy and agree to its terms.":"Al acceder y utilizar este Sitio Web, los usuarios reconocen haber leído y comprendido esta Política de Privacidad y aceptan sus condiciones.",
    "2. Data Controller":"2. Responsable del tratamiento",
    "The data controller responsible for the processing of personal data collected through this Website is the organization responsible for the event and its official communication channels.":"El responsable del tratamiento de los datos personales recogidos a través de este Sitio Web es la organización responsable del evento y de sus canales oficiales de comunicación.",
    "For any questions related to data protection, privacy, or the exercise of user rights, you may contact us through the contact information provided on the Website.":"Para cualquier consulta relacionada con la protección de datos, la privacidad o el ejercicio de los derechos de los usuarios, puede contactarse a través de la información de contacto disponible en el Sitio Web.",
    "3. Personal Data Collected":"3. Datos personales tratados",
    "This Website does not actively collect personal data through registration forms, user accounts, or third-party tracking systems.":"Este Sitio Web no recopila activamente datos personales mediante formularios de registro, cuentas de usuario ni sistemas de seguimiento de terceros.",
    "However, personal data may appear on the Website in the following contexts:":"No obstante, pueden aparecer datos personales en el Sitio Web en los siguientes contextos:",
    "Images and audiovisual material":"Imágenes y material audiovisual",
    "(photographs and videos) taken during public events.":"(fotografías y vídeos) captados durante eventos de carácter público.",
    "Information related to participants":"Información relativa a personas participantes",
    ", such as artists, performers, speakers, volunteers, collaborators, or sponsors.":", tales como artistas, intérpretes, ponentes, voluntarios, colaboradores o patrocinadores.",
    "Publicly available information":"Información de carácter público",
    "provided voluntarily by the individuals involved in the event.":"facilitada voluntariamente por las personas involucradas en el evento.",
    "No sensitive personal data is intentionally collected or processed.":"No se recogen ni tratan de forma intencionada datos personales de carácter sensible.",
    "4. Images, Photography, and Audiovisual Content":"4. Imágenes, fotografía y material audiovisual",
    "During the event, photographs and videos may be taken for documentation, promotional, and communication purposes. These materials may be published on this Website and other official communication channels related to the event.":"Durante la celebración del evento, pueden tomarse fotografías y grabaciones de vídeo con fines documentales, promocionales y comunicativos. Dichos materiales podrán publicarse en este Sitio Web y en otros canales oficiales relacionados con el evento.",
    "By attending the event, individuals acknowledge and accept that:":"La asistencia al evento implica que las personas asistentes reconocen y aceptan que:",
    "Their image may be captured incidentally or intentionally in public areas.":"Su imagen pueda ser captada de forma incidental o intencionada en espacios públicos.",
    "Such images may be used for informational, promotional, and archival purposes.":"Dichas imágenes puedan utilizarse con fines informativos, promocionales y de archivo.",
    "No commercial exploitation of individual images will take place beyond the promotion and communication of the event itself.":"No se realizará una explotación comercial individualizada de las imágenes más allá de la promoción y comunicación del propio evento.",
    "If any individual considers that their image has been published inappropriately or wishes to request its removal, they may contact the organization, and reasonable measures will be taken where applicable.":"En caso de que una persona considere que su imagen ha sido publicada de forma inadecuada o desee solicitar su retirada, podrá contactar con la organización y se adoptarán las medidas razonables que resulten procedentes.",
    "5. Purpose of Data Processing":"5. Finalidad del tratamiento",
    "Any personal data appearing on the Website is processed exclusively for the following purposes:":"Los datos personales que puedan aparecer en el Sitio Web se tratan exclusivamente con las siguientes finalidades:",
    "Promotion and documentation of the event.":"Promoción y documentación del evento.",
    "Informational content related to participants and activities.":"Difusión de información relacionada con las personas participantes y las actividades desarrolladas.",
    "Communication with the public regarding past, current, or future editions of the event.":"Comunicación con el público sobre ediciones pasadas, presentes o futuras del evento.",
    "Personal data will not be used for profiling, automated decision-making, or commercial data trading.":"En ningún caso los datos personales se utilizarán para la elaboración de perfiles, la toma de decisiones automatizadas ni para la comercialización de datos.",
    "6. Legal Basis for Processing":"6. Base legal del tratamiento",
    "The legal basis for processing personal data includes:":"La base legal para el tratamiento de los datos personales incluye:",
    "Legitimate interest":"El interés legítimo",
    "in promoting and documenting a public cultural or social event.":"en la promoción y documentación de un evento cultural o social de carácter público.",
    "Consent":"El consentimiento",
    ", where applicable, provided explicitly or implicitly through participation in the event.":", cuando resulte aplicable, otorgado de forma expresa o implícita mediante la participación en el evento.",
    "Public interest":"El interés público",
    ", when the event is open to the general public.":", cuando el evento esté abierto al público general.",
    "7. Data Retention":"7. Conservación de los datos",
    "Personal data, including images and related content, will be retained only for as long as necessary to fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law.":"Los datos personales, incluidas las imágenes y contenidos asociados, se conservarán únicamente durante el tiempo necesario para cumplir las finalidades descritas en esta Política de Privacidad, salvo que la normativa aplicable exija o permita un plazo de conservación superior.",
    "8. Data Sharing":"8. Cesión de datos",
    "The Website does not share personal data with third parties, except when legally required or when necessary for the technical operation of the Website (e.g., hosting services), under appropriate data protection safeguards.":"El Sitio Web no cede datos personales a terceros, salvo en los casos legalmente exigidos o cuando sea necesario para el funcionamiento técnico del Sitio Web (por ejemplo, servicios de alojamiento), siempre bajo las debidas garantías de protección de datos.",
    "No data is sold, transferred, or shared for commercial purposes.":"No se venden, transfieren ni comparten datos personales con fines comerciales.",
    "9. User Rights":"9. Derechos de las personas interesadas",
    "In accordance with the GDPR, individuals have the right to:":"De conformidad con el RGPD, las personas interesadas tienen derecho a:",
    "Access their personal data.":"Acceder a sus datos personales.",
    "Request rectification or deletion of their data.":"Solicitar la rectificación o supresión de sus datos.",
    "Object to or restrict the processing of their data.":"Oponerse al tratamiento o solicitar su limitación.",
    "Request the removal of images or content where legally applicable.":"Solicitar la retirada de imágenes o contenidos cuando resulte legalmente procedente.",
    "Requests must be submitted through the contact details provided on the Website and will be addressed within the legally established timeframes.":"Las solicitudes deberán realizarse a través de los datos de contacto facilitados en el Sitio Web y serán atendidas dentro de los plazos legalmente establecidos.",
    "10. Intellectual Property and Content Rights":"10. Propiedad intelectual y derechos sobre los contenidos",
    "All content published on the Website, including but not limited to photographs, videos, graphic design, text, and website layout, is protected by intellectual property and copyright laws.":"Todos los contenidos publicados en el Sitio Web, incluyendo, entre otros, fotografías, vídeos, diseño gráfico, textos y estructura del sitio, están protegidos por la normativa sobre propiedad intelectual y derechos de autor.",
    "Unauthorized reproduction, distribution, or use of such content without prior consent is strictly prohibited.":"Queda expresamente prohibida la reproducción, distribución o utilización de dichos contenidos sin la autorización previa correspondiente.",
    "11. Liability Disclaimer":"11. Exención de responsabilidad",
    "The organization shall not be held responsible for:":"La organización no será responsable de:",
    "The use of images or information by third parties without authorization.":"El uso no autorizado de imágenes o información por parte de terceros.",
    "Content shared externally beyond the control of the Website.":"Contenidos compartidos fuera del control del Sitio Web.",
    "Incidental appearance of individuals in public event imagery.":"La aparición incidental de personas en imágenes de eventos públicos.",
    "The Website is provided “as is” and is intended solely for informational and promotional purposes.":"El Sitio Web se ofrece “tal cual” y tiene exclusivamente fines informativos y promocionales.",
    "12. Policy Updates":"12. Modificaciones de la política",
    "This Privacy Policy may be updated at any time to reflect legal, technical, or operational changes. Users are encouraged to review this page periodically.":"a presente Política de Privacidad podrá actualizarse en cualquier momento para reflejar cambios legales, técnicos u operativos. Se recomienda a los usuarios revisar periódicamente esta página.",
    "13. Contact":"13. Contacto",
    "For any questions regarding this Privacy Policy or the handling of personal data, please refer to the contact section of the Website.":"Para cualquier consulta relacionada con esta Política de Privacidad o con el tratamiento de datos personales, puede consultarse la sección de contacto del Sitio Web.",
});
Object.assign(window.translations.Català, {
    "1. Introduction":"1. Introducció",
    "This Privacy Policy explains how this website (hereinafter referred to as “the Website”) collects, uses, and protects personal data, in accordance with Regulation (EU) 2016/679 of the European Parliament and of the Council (General Data Protection Regulation – GDPR), and applicable data protection laws.":"La present Política de Privacitat explica com aquest lloc web (d’ara endavant, el “Lloc Web”) recopila, utilitza i protegeix les dades personals, d’acord amb el Reglament (UE) 2016/679 del Parlament Europeu i del Consell (Reglament General de Protecció de Dades – RGPD) i la normativa aplicable en matèria de protecció de dades.",
    "By accessing and using this Website, users acknowledge that they have read and understood this Privacy Policy and agree to its terms.":"L’accés i ús d’aquest Lloc Web implica que els usuaris reconeixen haver llegit i entès aquesta Política de Privacitat i n’accepten les condicions.",
    "2. Data Controller":"2. Responsable del tractament",
    "The data controller responsible for the processing of personal data collected through this Website is the organization responsible for the event and its official communication channels.":"El responsable del tractament de les dades personals recollides a través d’aquest Lloc Web és l’organització responsable de l’esdeveniment i dels seus canals oficials de comunicació.",
    "For any questions related to data protection, privacy, or the exercise of user rights, you may contact us through the contact information provided on the Website.":"Per a qualsevol consulta relacionada amb la protecció de dades, la privacitat o l’exercici dels drets de les persones usuàries, es pot contactar mitjançant la informació de contacte disponible al Lloc Web.",
    "3. Personal Data Collected":"3. Dades personals tractades",
    "This Website does not actively collect personal data through registration forms, user accounts, or third-party tracking systems.":"Aquest Lloc Web no recull activament dades personals mitjançant formularis de registre, comptes d’usuari ni sistemes de seguiment de tercers.",
    "However, personal data may appear on the Website in the following contexts:":"Tanmateix, poden aparèixer dades personals al Lloc Web en els contextos següents:",
    "Images and audiovisual material":"Imatges i material audiovisual",
    "(photographs and videos) taken during public events.":"(fotografies i vídeos) captats durant esdeveniments de caràcter públic.",
    "Information related to participants":"Informació relativa a persones participants",
    ", such as artists, performers, speakers, volunteers, collaborators, or sponsors.":", com ara artistes, intèrprets, ponents, voluntaris, col·laboradors o patrocinadors.",
    "Publicly available information":"Informació de caràcter públic",
    "provided voluntarily by the individuals involved in the event.":"facilitada voluntàriament per les persones involucrades en l’esdeveniment.",
    "No sensitive personal data is intentionally collected or processed.":"No es recullen ni es tracten de manera intencionada dades personals de caràcter sensible.",
    "4. Images, Photography, and Audiovisual Content":"4. Imatges, fotografia i material audiovisual",
    "During the event, photographs and videos may be taken for documentation, promotional, and communication purposes. These materials may be published on this Website and other official communication channels related to the event.":"Durant la celebració de l’esdeveniment, es poden realitzar fotografies i gravacions de vídeo amb finalitats documentals, promocionals i comunicatives. Aquests materials es poden publicar en aquest Lloc Web i en altres canals oficials relacionats amb l’esdeveniment.",
    "By attending the event, individuals acknowledge and accept that:":"L’assistència a l’esdeveniment implica que les persones assistents reconeixen i accepten que:",
    "Their image may be captured incidentally or intentionally in public areas.":"La seva imatge pugui ser captada de manera incidental o intencionada en espais públics.",
    "Such images may be used for informational, promotional, and archival purposes.":"Aquestes imatges es puguin utilitzar amb finalitats informatives, promocionals i d’arxiu.",
    "No commercial exploitation of individual images will take place beyond the promotion and communication of the event itself.":"No es durà a terme una explotació comercial individualitzada de les imatges més enllà de la promoció i comunicació del propi esdeveniment.",
    "If any individual considers that their image has been published inappropriately or wishes to request its removal, they may contact the organization, and reasonable measures will be taken where applicable.":"En cas que una persona consideri que la seva imatge s’ha publicat de manera inadequada o desitgi sol·licitar-ne la retirada, pot contactar amb l’organització i s’adoptaran les mesures raonables que corresponguin.",
    "5. Purpose of Data Processing":"5. Finalitat del tractament",
    "Any personal data appearing on the Website is processed exclusively for the following purposes:":"Les dades personals que puguin aparèixer al Lloc Web es tracten exclusivament amb les finalitats següents:",
    "Promotion and documentation of the event.":"Promoció i documentació de l’esdeveniment.",
    "Informational content related to participants and activities.":"Difusió d’informació relacionada amb les persones participants i les activitats realitzades.",
    "Communication with the public regarding past, current, or future editions of the event.":"Comunicació amb el públic sobre edicions passades, presents o futures de l’esdeveniment.",
    "Personal data will not be used for profiling, automated decision-making, or commercial data trading.":"En cap cas les dades personals s’utilitzaran per a l’elaboració de perfils, la presa de decisions automatitzades ni per a la comercialització de dades.",
    "6. Legal Basis for Processing":"6. Base legal del tractament",
    "The legal basis for processing personal data includes:":"La base legal per al tractament de les dades personals inclou:",
    "Legitimate interest":"L’interès legítim",
    "in promoting and documenting a public cultural or social event.":"en la promoció i documentació d’un esdeveniment cultural o social de caràcter públic.",
    "Consent":"El consentiment",
    ", where applicable, provided explicitly or implicitly through participation in the event.":", quan sigui aplicable, atorgat de manera expressa o implícita mitjançant la participació en l’esdeveniment.",
    "Public interest":"L’interès públic",
    ", when the event is open to the general public.":", quan l’esdeveniment estigui obert al públic general.",
    "7. Data Retention":"7. Conservació de les dades",
    "Personal data, including images and related content, will be retained only for as long as necessary to fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law.":"Les dades personals, incloses les imatges i els continguts associats, es conservaran únicament durant el temps necessari per complir les finalitats descrites en aquesta Política de Privacitat, llevat que la normativa aplicable exigeixi o permeti un termini de conservació superior.",
    "8. Data Sharing":"8. Comunicació de dades",
    "The Website does not share personal data with third parties, except when legally required or when necessary for the technical operation of the Website (e.g., hosting services), under appropriate data protection safeguards.":"El Lloc Web no comunica dades personals a tercers, excepte en els casos legalment exigits o quan sigui necessari per al funcionament tècnic del Lloc Web (per exemple, serveis d’allotjament), sempre sota les garanties adequades de protecció de dades.",
    "No data is sold, transferred, or shared for commercial purposes.":"No es venen, transfereixen ni comparteixen dades personals amb finalitats comercials.",
    "9. User Rights":"9. Drets de les persones interessades",
    "In accordance with the GDPR, individuals have the right to:":"D’acord amb el RGPD, les persones interessades tenen dret a:",
    "Access their personal data.":"Accedir a les seves dades personals.",
    "Request rectification or deletion of their data.":"Sol·licitar la rectificació o supressió de les dades.",
    "Object to or restrict the processing of their data.":"Oposar-se al tractament o sol·licitar-ne la limitació.",
    "Request the removal of images or content where legally applicable.":"Sol·licitar la retirada d’imatges o continguts quan sigui legalment procedent.",
    "Requests must be submitted through the contact details provided on the Website and will be addressed within the legally established timeframes.":"Les sol·licituds s’han de realitzar mitjançant les dades de contacte facilitades al Lloc Web i es resoldran dins dels terminis legalment establerts.",
    "10. Intellectual Property and Content Rights":"10. Propietat intel·lectual i drets sobre els continguts",
    "All content published on the Website, including but not limited to photographs, videos, graphic design, text, and website layout, is protected by intellectual property and copyright laws.":"Tots els continguts publicats al Lloc Web, incloent-hi, entre d’altres, fotografies, vídeos, disseny gràfic, textos i estructura del lloc, estan protegits per la normativa de propietat intel·lectual i drets d’autor.",
    "Unauthorized reproduction, distribution, or use of such content without prior consent is strictly prohibited.":"Queda expressament prohibida la reproducció, distribució o utilització d’aquests continguts sense l’autorització prèvia corresponent.",
    "11. Liability Disclaimer":"11. Exempció de responsabilitat",
    "The organization shall not be held responsible for:":"L’organització no serà responsable de:",
    "The use of images or information by third parties without authorization.":"L’ús no autoritzat d’imatges o informació per part de tercers.",
    "Content shared externally beyond the control of the Website.":"Continguts compartits fora del control del Lloc Web.",
    "Incidental appearance of individuals in public event imagery.":"L’aparició incidental de persones en imatges d’esdeveniments públics.",
    "The Website is provided “as is” and is intended solely for informational and promotional purposes.":"El Lloc Web s’ofereix “tal com és” i té exclusivament finalitats informatives i promocionals.",
    "12. Policy Updates":"12. Modificacions de la política",
    "This Privacy Policy may be updated at any time to reflect legal, technical, or operational changes. Users are encouraged to review this page periodically.":"Aquesta Política de Privacitat pot actualitzar-se en qualsevol moment per reflectir canvis legals, tècnics o operatius. Es recomana a les persones usuàries revisar periòdicament aquesta pàgina.",
    "13. Contact":"13. Contacte",
    "For any questions regarding this Privacy Policy or the handling of personal data, please refer to the contact section of the Website.":"Per a qualsevol consulta relacionada amb aquesta Política de Privacitat o amb el tractament de dades personals, es pot consultar la secció de contacte del Lloc Web.",
});
Object.assign(window.translations.日本語, {
    "1. Introduction":"1. はじめに",
    "This Privacy Policy explains how this website (hereinafter referred to as “the Website”) collects, uses, and protects personal data, in accordance with Regulation (EU) 2016/679 of the European Parliament and of the Council (General Data Protection Regulation – GDPR), and applicable data protection laws.":"本プライバシーポリシーは、本ウェブサイト（以下「本サイト」）における個人情報の取り扱いについて、欧州議会および理事会規則（EU）2016/679（一般データ保護規則、以下「GDPR」）および関連法令に基づき説明するものです",
    "By accessing and using this Website, users acknowledge that they have read and understood this Privacy Policy and agree to its terms.":"本サイトにアクセスまたは利用することにより、利用者は本プライバシーポリシーの内容を理解し、これに同意したものとみなされます。",
    "2. Data Controller":"2. 個人情報取扱責任者",
    "The data controller responsible for the processing of personal data collected through this Website is the organization responsible for the event and its official communication channels.":"本サイトを通じて収集される個人情報の取扱責任者は、イベントの主催者および公式コミュニケーションを管理する組織です。",
    "For any questions related to data protection, privacy, or the exercise of user rights, you may contact us through the contact information provided on the Website.":"個人情報の保護、プライバシー、または利用者の権利行使に関するお問い合わせについては、本サイトに記載されている連絡先をご利用ください。",
    "3. Personal Data Collected":"3. 取り扱う個人情報の種類",
    "This Website does not actively collect personal data through registration forms, user accounts, or third-party tracking systems.":"本サイトでは、登録フォーム、ユーザーアカウント、第三者による追跡システムを通じて、利用者の個人情報を積極的に収集することはありません。",
    "However, personal data may appear on the Website in the following contexts:":"ただし、以下の状況において個人情報が掲載される場合があります。",
    "Images and audiovisual material":"公開イベント中に撮影された写真および映像",
    "(photographs and videos) taken during public events.":"（写真および動画）。",
    "Information related to participants":"イベントに参加する人物に関する情報",
    ", such as artists, performers, speakers, volunteers, collaborators, or sponsors.":"（アーティスト、出演者、講演者、ボランティア、協力者、またはスポンサーなど）。",
    "Publicly available information":"イベントに関与する個人が自発的に提供した公開情報",
    "provided voluntarily by the individuals involved in the event.":"。",
    "No sensitive personal data is intentionally collected or processed.":"要配慮個人情報が意図的に収集または処理されることはありません。",
    "4. Images, Photography, and Audiovisual Content":"4. 写真・映像および音声コンテンツについて",
    "During the event, photographs and videos may be taken for documentation, promotional, and communication purposes. These materials may be published on this Website and other official communication channels related to the event.":"イベント開催中、記録、広報、情報提供を目的として、写真撮影および動画撮影が行われる場合があります。これらのコンテンツは、本サイトおよび関連する公式媒体に掲載されることがあります。",
    "By attending the event, individuals acknowledge and accept that:":"イベントに参加することにより、参加者は以下の点を理解し、同意したものとみなされます。",
    "Their image may be captured incidentally or intentionally in public areas.":"公共の場において、意図的または偶発的に撮影される可能性があること",
    "Such images may be used for informational, promotional, and archival purposes.":"撮影された画像が、情報提供、広報、記録の目的で使用される可能性があること",
    "No commercial exploitation of individual images will take place beyond the promotion and communication of the event itself.":"イベントの宣伝を超えた、個別的または商業的な利用は行われないこと",
    "If any individual considers that their image has been published inappropriately or wishes to request its removal, they may contact the organization, and reasonable measures will be taken where applicable.":"掲載された画像について不適切と感じた場合、または削除を希望する場合は、主催者へご連絡いただければ、合理的な範囲で対応いたします。",
    "5. Purpose of Data Processing":"5. 利用目的",
    "Any personal data appearing on the Website is processed exclusively for the following purposes:":"本サイトに掲載される可能性のある個人情報は、以下の目的にのみ使用されます。",
    "Promotion and documentation of the event.":"イベントの記録および広報",
    "Informational content related to participants and activities.":"参加者および実施内容に関する情報発信",
    "Communication with the public regarding past, current, or future editions of the event.":"過去・現在・将来のイベントに関する告知および情報提供",
    "Personal data will not be used for profiling, automated decision-making, or commercial data trading.":"個人情報は、プロファイリング、完全自動化された意思決定、またはデータの商業利用には使用されません。",
    "6. Legal Basis for Processing":"6. 処理の法的根拠",
    "The legal basis for processing personal data includes:":"個人情報の処理は、以下の法的根拠に基づいて行われます。",
    "Legitimate interest":"公開イベントの記録および広報に関する正当な利益",
    "in promoting and documenting a public cultural or social event.":"に基づく場合。",
    "Consent":"該当する場合における同意",
    ", where applicable, provided explicitly or implicitly through participation in the event.":"は、イベントへの参加を通じて与えられます。",
    "Public interest":"一般公開イベントにおける公共の利益",
    ", when the event is open to the general public.":"に基づく場合。",
    "7. Data Retention":"7. データの保存期間",
    "Personal data, including images and related content, will be retained only for as long as necessary to fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law.":"個人情報（写真や関連コンテンツを含む）は、本プライバシーポリシーに記載された目的を達成するために必要な期間のみ保存されます。ただし、法令によりより長い保存期間が求められる場合を除きます。",
    "8. Data Sharing":"8. 個人情報の第三者提供",
    "The Website does not share personal data with third parties, except when legally required or when necessary for the technical operation of the Website (e.g., hosting services), under appropriate data protection safeguards.":"本サイトは、法令に基づく場合または技術的運営上必要な場合（例：サーバー管理会社）を除き、個人情報を第三者に提供することはありません。",
    "No data is sold, transferred, or shared for commercial purposes.":"個人情報が商業目的で販売、譲渡、共有されることはありません。",
    "9. User Rights":"9. 利用者の権利",
    "In accordance with the GDPR, individuals have the right to:":"GDPRに基づき、利用者は以下の権利を有します。",
    "Access their personal data.":"自身の個人情報へのアクセス",
    "Request rectification or deletion of their data.":"個人情報の訂正または削除の請求",
    "Object to or restrict the processing of their data.":"個人情報の処理への異議申立てまたは制限の要求",
    "Request the removal of images or content where legally applicable.":"法的に認められる範囲での画像やコンテンツの削除請求",
    "Requests must be submitted through the contact details provided on the Website and will be addressed within the legally established timeframes.":"これらの権利行使は、本サイトに記載された連絡先を通じて行うことができます。",
    "10. Intellectual Property and Content Rights":"10. 知的財産権およびコンテンツの権利",
    "All content published on the Website, including but not limited to photographs, videos, graphic design, text, and website layout, is protected by intellectual property and copyright laws.":"本サイトに掲載されているすべてのコンテンツ（写真、映像、デザイン、テキスト、構成など）は、著作権および知的財産権により保護されています。",
    "Unauthorized reproduction, distribution, or use of such content without prior consent is strictly prohibited.":"事前の許可なく、これらのコンテンツを複製、配布、使用することは禁止されています。",
    "11. Liability Disclaimer":"11. 免責事項",
    "The organization shall not be held responsible for:":"主催者は、以下の事項について責任を負いません。",
    "The use of images or information by third parties without authorization.":"第三者による画像や情報の無断使用",
    "Content shared externally beyond the control of the Website.":"本サイトの管理外で共有されたコンテンツ",
    "Incidental appearance of individuals in public event imagery.":"公開イベントにおいて偶発的に写り込んだ人物の画像",
    "The Website is provided “as is” and is intended solely for informational and promotional purposes.":"本サイトは「現状有姿」で提供され、情報提供および広報のみを目的としています。",
    "12. Policy Updates":"12. プライバシーポリシーの変更",
    "This Privacy Policy may be updated at any time to reflect legal, technical, or operational changes. Users are encouraged to review this page periodically.":"本プライバシーポリシーは、法令、技術、運営上の変更に応じて、予告なく更新されることがあります。利用者は定期的に本ページを確認することを推奨します。",
    "13. Contact":"13. お問い合わせ",
    "For any questions regarding this Privacy Policy or the handling of personal data, please refer to the contact section of the Website.":"本プライバシーポリシーまたは個人情報の取り扱いに関するお問い合わせは、本サイトのお問い合わせページをご参照ください。",
});