window.translations = window.translations || {
    Español: {},
    Català: {},
    日本語: {}
};
Object.assign(window.translations.Español, {
    "About Matsuri BCN":"Acerca de Matsuri BCN",
    "Frequent Asked Questions":"Preguntas frecuentes",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.":"La Asociación de Cultura Japonesa Matsuri (マツリ日本文化協会) es una entidad sin ánimo de lucro con más de 13 años de recorrido en Barcelona. Desde que empezamos en 2013, trabajamos para acercar la cultura japonesa al público de forma abierta y accesible, pasando de una primera edición 1.500 personas a un festival consolidado que reunió a más de 40.000 asistentes en 2024.",
    "This growth has been made possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association’s president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural promotion. Our main asset is human capital. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural, inclusive perspective deeply connected to Barcelona’s cultural fabric.":"Este crecimiento ha sido posible gracias al compromiso del equipo, la implicación de la comunidad y una programación cultural diversa. En 2019, esta labor fue reconocida oficialmente cuando el presidente de la asociación recibió la Distinción del Cónsul General del Japón en Barcelona por su contribución a la difusión cultural. Nuestro principal valor es el capital humano. Contamos con más de 130 voluntarios de hasta 20 orígenes distintos, lo que nos permite trabajar desde una perspectiva intercultural, inclusiva y profundamente vinculada al tejido cultural de Barcelona.",
    "What are the event hours?":"¿Cuál es el horario del evento?",
    "Access to Matsuri will be open from 11:00 AM to 8:00 PM. The event will close at 9:00 PM on both days.":"Se podrá acceder a Matsuri desde las 11h hasta las 20h, el evento se cerrará a las 21h ambos días.",
    "Do I need to buy a ticket to attend?":"¿Es necesario comprar entradas para asistir?",
    "Yes. Matsuri is a non-profit event largely created by volunteers, and your contribution is very important to make Matsuri possible. You can purchase your ticket at":"Sí, Matsuri es un evento sin ánimo de lucro creado mayormente por voluntarios, tu aportación es muy importante para poder hacer Matsuri. Puedes comprar tu entrada en",
    "There are discounts for early ticket purchases!":"¡Hay descuentos por compra anticipada!",
    "Admission is free for those born on or after January 1st, 2014 (inclusive), and for people with disabilities and one accompanying person. An official certificate may be requested (official resolutions are accepted even with a disability degree below 33%).":"La entrada es gratuita para los nacidos a partir del 1 de enero de 2014 (inclusive) y para personas con discapacidad y un acompañante. Se podrá solicitar certificado oficial (se aceptará resolución oficial incluso con grado inferior al 33%).",
    "Can I leave and re-enter the venue?":"¿Puedo salir y volver a entrar al recinto?",
    "No. For safety and capacity reasons, re-entry is not allowed. We recommend coming to spend the whole day, as there are many activities you will love, as well as a food area.":"No, por normas de seguridad y aforo no se permite salir y volver a entrar. Te recomendamos que vengas a pasar el día, ya que hay todo tipo de actividades que te encantarán y también zona de restauración.",
    "Can I enter with my scooter or bicycle?":"¿Puedo acceder con mi patinete o bicicleta?",
    "Access with scooters, bicycles, or other vehicles is not permitted.":"No se permite el acceso con patinetes, bicicletas u otros vehículos.",
    "Can I enter with food or drinks?":"¿Puedo acceder con comida o bebida?",
    "Exception:":"Excepción:",
    "only":"se permite únicamente el acceso con",
    "WATER":"AGUA",
    "is permitted (to prevent heatstroke).":"(por prevención de golpes de calor).",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"(Sostenibilidad: Recomendamos el uso de botellas reutilizables para reducir el plástico).",
    "Can I bring my dog?":"¿Puedo ir con mi perro?",
    "Yes, dogs are also part of the family, but they must be kept on a leash. Please help us keep the venue clean by taking responsibility for their waste. Keep in mind that Matsuri can be crowded and noisy, which may be stressful for them.":"Sí, los perros también son parte de la familia, pero deben ir atados con correa y, por favor, ayúdanos a mantener el recinto limpio haciéndote cargo de sus deposiciones. Ten en cuenta que en Matsuri hay mucha gente y ruidos que le pueden asustar.",
    "Do I need to register in advance for the workshops?":"¿Es necesario inscribirse previamente en los talleres?",
    "Some workshops require prior registration. Our staff at the Information stand located at the entrance will be happy to help you.":"Algunos talleres requieren inscribirse previamente. En el stand de Información que encontrarás en la entrada te ayudaremos.",
    "Is there vegetarian or vegan food available?":"¿Hay comida vegetariana o vegana?",
    "Yes, there are options for everyone.":"Sí, hay opciones para todos.",
    "How can I participate as a volunteer?":"¿Cómo puedo participar como voluntario?",
    "Please fill out this form and we will contact you as soon as possible":"Por favor, rellena este formulario y nos pondremos en contacto contigo lo antes posible",
    "here":"aquí",
    "How can I collaborate as a sponsor?":"¿Cómo puedo colaborar como patrocinador?",
//
    "How can I participate as an artist or cultural group?":"¿Cómo puedo participar como artista o grupo cultural?",
//
    "How can I participate in the food area?":"¿Cómo puedo participar en la zona de restauración?",
    "Please fill out this form and we will contact you as soon as possible":"Por favor, rellena este formulario y nos pondremos en contacto contigo lo antes posible",
    "Is there a children’s area?":"¿Hay zona para los niños?",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age. Children must always be accompanied by an adult.":"Matsuri cuenta con una zona especial para niños, donde podrán disfrutar de actividades adaptadas a su edad, pero deben de ir siempre acompañados de un adulto.",
});
Object.assign(window.translations.Català, {
    "About Matsuri BCN":"Sobre Matsuri BCN",
    "Frequent Asked Questions":"Preguntes freqüents",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.":"L’Associació de Cultura Japonesa Matsuri (マツリ日本文化協会) és una entitat sense ànim de lucre amb més de 13 anys d’experiència a Barcelona. Des que vam començar el 2013, treballem per acostar la cultura japonesa al públic de manera oberta i accessible, passant de 1.500 persones a la primera edició a un festival consolidat que va reunir més de 40.000 assistents el 2024.",
    "This growth has been made possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association’s president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural promotion. Our main asset is human capital. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural, inclusive perspective deeply connected to Barcelona’s cultural fabric.":"Aquest creixement ha estat possible gràcies al compromís de l’equip, la implicació de la comunitat i una programació cultural diversa. El 2019, aquesta tasca va ser reconeguda oficialment quan el president de l’associació va rebre la Distinció del Consol General del Japó a Barcelona per la seva contribució a la difusió cultural. El nostre principal valor és el capital humà. Comptem amb més de 130 voluntaris procedents de fins a 20 orígens diferents, cosa que ens permet treballar des d’una perspectiva intercultural, inclusiva i profundament vinculada al teixit cultural de Barcelona.",
    "What are the event hours?":"Quin és l’horari de l’esdeveniment?",
    "Access to Matsuri will be open from 11:00 AM to 8:00 PM. The event will close at 9:00 PM on both days.":"Es podrà accedir al Matsuri de les 11 h fins a les 20 h. L’esdeveniment es tancarà a les 21 h els dos dies.",
    "Do I need to buy a ticket to attend?":"Cal comprar entrada per assistir-hi?",
    "Yes. Matsuri is a non-profit event largely created by volunteers, and your contribution is very important to make Matsuri possible. You can purchase your ticket at":"Sí. Matsuri és un esdeveniment sense ànim de lucre creat majoritàriament per voluntaris, i la teva aportació és molt important per poder fer possible el Matsuri. Pots comprar la teva entrada a",
    "There are discounts for early ticket purchases!":"Hi ha descomptes per compra anticipada!",
    "Admission is free for those born on or after January 1st, 2014 (inclusive), and for people with disabilities and one accompanying person. An official certificate may be requested (official resolutions are accepted even with a disability degree below 33%).":"L’entrada és gratuïta per a les persones nascudes a partir de l’1 de gener de 2014 (inclòs) i per a persones amb discapacitat i un acompanyant. Es podrà sol·licitar certificat oficial (s’acceptarà resolució oficial fins i tot amb un grau inferior al 33%).",
    "Can I leave and re-enter the venue?":"Puc sortir i tornar a entrar al recinte?",
    "No. For safety and capacity reasons, re-entry is not allowed. We recommend coming to spend the whole day, as there are many activities you will love, as well as a food area.":"No. Per motius de seguretat i aforament no està permès sortir i tornar a entrar. Et recomanem venir a passar el dia sencer, ja que hi ha moltes activitats que t’encantaran i també zona de restauració.",
    "Can I enter with my scooter or bicycle?":"Puc accedir amb el meu patinet o bicicleta?",
    "Access with scooters, bicycles, or other vehicles is not permitted.":"No es permet l’accés amb patinets, bicicletes ni altres vehicles.",
    "Can I enter with food or drinks?":"Puc accedir amb menjar o beguda?",
    "Exception:":"Excepció:",
    "only":"només es permet l’accés amb",
    "WATER":"AIGUA",
    "is permitted (to prevent heatstroke).":"(per prevenir cops de calor).",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"(Sostenibilitat: Recomanem l’ús d’ampolles reutilitzables per reduir el plàstic).",
    "Can I bring my dog?":"Puc anar amb el meu gos?",
    "Yes, dogs are also part of the family, but they must be kept on a leash. Please help us keep the venue clean by taking responsibility for their waste. Keep in mind that Matsuri can be crowded and noisy, which may be stressful for them.":"Sí, els gossos també són part de la família, però han d’anar lligats amb corretja. Si us plau, ajuda’ns a mantenir el recinte net fent-te càrrec de les seves deposicions. Tingues en compte que a Matsuri hi ha molta gent i sorolls que el poden espantar.",
    "Do I need to register in advance for the workshops?":"Cal inscriure’s prèviament als tallers?",
    "Some workshops require prior registration. Our staff at the Information stand located at the entrance will be happy to help you.":"Alguns tallers requereixen inscripció prèvia. Al punt d’Informació que trobaràs a l’entrada t’ajudarem.",
    "Is there vegetarian or vegan food available?":"Hi ha menjar vegetarià o vegà?",
    "Yes, there are options for everyone.":"Sí, hi ha opcions per a tothom.",
    "How can I participate as a volunteer?":"Com puc participar com a voluntari/ària?",
    "Please fill out this form and we will contact you as soon as possible":"Si us plau, omple aquest formulari i ens posarem en contacte amb tu tan aviat com sigui possible",
    "here":"aquí",
    "How can I collaborate as a sponsor?":"Com puc col·laborar com a patrocinador?",
//
    "How can I participate as an artist or cultural group?":"Com puc participar com a artista o grup cultural?",
//
    "How can I participate in the food area?":"Com puc participar a la zona de restauració?",
    "Please fill out this form and we will contact you as soon as possible":"Si us plau, omple aquest formulari i ens posarem en contacte amb tu tan aviat com sigui possible",
    "Is there a children’s area?":"Hi ha una zona per a nens?",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age. Children must always be accompanied by an adult.":"Matsuri compta amb una zona especial per a nens, on podran gaudir d’activitats adaptades a la seva edat, però sempre han d’anar acompanyats d’un adult.",
});
Object.assign(window.translations.日本語, {
    "About Matsuri BCN":"Matsuri BCNについて",
    "Frequent Asked Questions":"よくある質問",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.":"Matsuri日本文化協会（Matsuri Japanese Culture Association）は、バルセロナで13年以上の歴史を持つ非営利団体です。2013年の設立以来、私たちは日本文化を広く誰でも楽しめる形で紹介することに取り組んできました。初回の来場者1,500人から、2024年には4万人以上を動員するフェスティバルへと成長しました。この成長は、献身的なチーム、地域コミュニティのサポート、多様な文化プログラムのおかげで実現しました。2019年には、この活動が正式に評価され、協会の代表がバルセロナ日本国総領事より文化普及への貢献として表彰を受けました。私たちの最大の資産は人材です。20以上の異なるバックグラウンドを持つ130人以上のボランティアがおり、これによりバルセロナの文化的ネットワークと深く結びつきながら、異文化的で包括的な視点から活動することが可能になっています。",
    "This growth has been made possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association’s president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural promotion. Our main asset is human capital. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural, inclusive perspective deeply connected to Barcelona’s cultural fabric.":"マツリ日本文化協会（Matsuri Japanese Culture Association）は、バルセロナで13年以上の歴史を持つ非営利団体です。2013年の設立以来、私たちは日本文化を広く誰でも楽しめる形で紹介することに取り組んできました。初回の来場者1,500人から、2024年には4万人以上を動員する確立されたフェスティバルへと成長しました。この成長は、チームの献身、コミュニティの関与、多様な文化プログラムのおかげで実現しました。2019年には、この活動が正式に評価され、協会の代表がバルセロナ日本国総領事より文化普及への貢献として表彰を受けました。私たちの最大の資産は人材です。20以上の異なるバックグラウンドを持つ130人以上のボランティアがおり、これによりバルセロナの文化的ネットワークと深く結びつきながら、異文化的で包括的な視点から活動することが可能になっています。",
    "What are the event hours?":"イベントの開催時間は何時ですか？",
    "Access to Matsuri will be open from 11:00 AM to 8:00 PM. The event will close at 9:00 PM on both days.":"祭りは11時から20時まで入場可能です。両日ともイベントは21時に終了します。",
    "Do I need to buy a ticket to attend?":"参加するにはチケットの購入が必要ですか？",
    "Yes. Matsuri is a non-profit event largely created by volunteers, and your contribution is very important to make Matsuri possible. You can purchase your ticket at":"はい。祭りは主にボランティアによって運営されている非営利イベントであり、皆さまのご協力が祭りの開催にとって非常に重要です。チケットは以下のリンクから購入できます。",
    "There are discounts for early ticket purchases!":"前売り割引があります！",
    "Admission is free for those born on or after January 1st, 2014 (inclusive), and for people with disabilities and one accompanying person. An official certificate may be requested (official resolutions are accepted even with a disability degree below 33%).":"2014年1月1日以降（同日含む）に生まれた方、および障がいのある方とその付き添いの方1名は入場無料です。公式証明書の提示をお願いする場合があります（障がい等級が33％未満の場合でも、公式な認定書があれば受け付けます）。",
    "Can I leave and re-enter the venue?":"会場から一度出て、再入場することはできますか？",
    "No. For safety and capacity reasons, re-entry is not allowed. We recommend coming to spend the whole day, as there are many activities you will love, as well as a food area.":"いいえ。安全および収容人数の都合上、再入場はできません。ぜひ一日を通してお楽しみください。魅力的なアクティビティや飲食エリアもご用意しています。",
    "Can I enter with my scooter or bicycle?":"キックボードや自転車で入場できますか？",
    "Access with scooters, bicycles, or other vehicles is not permitted.":"キックボード、自転車、その他の乗り物での入場はできません。",
    "Can I enter with food or drinks?":"食べ物や飲み物を持ち込むことはできますか？",
    "Exception:":"例外:",
    "only":"熱中症予防のため、",
    "WATER":"水のみ",
    "is permitted (to prevent heatstroke).":"持ち込み可能です",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"（サステナビリティ：プラスチック削減のため、再利用可能なボトルの使用を推奨しています。）",
    "Can I bring my dog?":"犬を連れて行ってもいいですか？",
    "Yes, dogs are also part of the family, but they must be kept on a leash. Please help us keep the venue clean by taking responsibility for their waste. Keep in mind that Matsuri can be crowded and noisy, which may be stressful for them.":"はい、犬も家族の一員ですが、必ずリードを着用してください。また、排泄物の処理にご協力いただき、会場を清潔に保つようお願いいたします。Matsuriは人が多く、音も大きいため、犬が怖がる場合がありますのでご注意ください。",
    "Do I need to register in advance for the workshops?":"ワークショップに事前登録は必要ですか？",
    "Some workshops require prior registration. Our staff at the Information stand located at the entrance will be happy to help you.":"一部のワークショップでは事前登録が必要です。入口にあるインフォメーションブースでスタッフがご案内します。",
    "Is there vegetarian or vegan food available?":"ベジタリアンやヴィーガン向けの食事はありますか？",
    "Yes, there are options for everyone.":"はい、どなたにもお楽しみいただける選択肢があります。",
    "How can I participate as a volunteer?":"ボランティアとして参加するにはどうすればいいですか？",
    "Please fill out this form and we will contact you as soon as possible":"以下のフォームにご記入ください。できるだけ早くご連絡いたします。",
    "here":"ここ",
    "How can I collaborate as a sponsor?":"スポンサーとして協力するにはどうすればいいですか？",
//
    "How can I participate as an artist or cultural group?":"アーティストや文化グループとして参加するにはどうすればいいですか？",
//
    "How can I participate in the food area?":"飲食エリアに参加するにはどうすればいいですか？",
    "Please fill out this form and we will contact you as soon as possible":"以下のフォームにご記入ください。できるだけ早くご連絡いたします。",
    "Is there a children’s area?":"子ども用エリアはありますか？",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age. Children must always be accompanied by an adult.":"Matsuriには子ども用の特別なエリアがあり、年齢に合わせたアクティビティを楽しむことができます。子どもは必ず大人の付き添いが必要です。",

});