const translations = {
    Español: {
      "Matsuri Barcelona Festival":"Festival Matsuri Barcelona",
      "MAY 16th and 17th - MOLL DE LA FUSTA":"16 y 17 DE MAYO - MOLL DE LA FUSTA",
      "Welcome": "Bienvenido",
      "Buy your tickets now": "Compra tus entradas ahora",
      "TICKETS": "ENTRADAS",
      "The Festival": "El Festival",
      "Activities": "Actividades",
      "Program": "Programa",
      "Artists": "Artistas",
      "Kids area": "Zona infantil",
      "Stands": "Stands",
      "Food and drinks": "Comida y bebida",
      "About":"Acerca de",
      "Support us":"Colabora",
      // "Support us":"Apóyanos",
      "Contact":"Contacto",
      "Sponsor us":"Patrocínanos",
      "Crowdfund us":"Crowdfunding",
      "Volunteering":"Voluntariado",
      "VALID TICKET SALES, ONLY THROUGH ENTRADIUM.COM":"VENTA DE ENTRADAS VÁLIDAS SOLO A TRAVÉS DE ENTRADIUM.COM",
      // -- ランタン --
      "Join the Matsuri":"Súmate al Matsuri",
      "We are opening the call for food vendors, exhibitors, and sponsors.":"Abrimos convocatoria para restauración, expositores y sponsors.",
      "If you want to take part in the festival, fill out the corresponding form.":"Si quieres participar en el festival, completa el formulario correspondiente.",
      "Choose your profile and send us your proposal.":"Elige tu perfil y envíanos tu propuesta.",
      "Food Vendors":"Restauración",
      "Exhibitors":"Expositores",
      "Sponsors":"Sponsors",
      // -------------
      "Stands":"Stands",
      "Crowdfunding":"Crowdfunding",
      "Matsuri 2026 Poster":"Poster Matsuri 2026",
      "We present our famous Matsuri Barcelona poster created every year by the tattoo artist": "Presentamos nuestro famoso cartel de Matsuri Barcelona creado cada año por el tatuador y artista",
      "Jun Chihara": "Jun Chihara",
      "The new 2026 poster reinterprets Japanese tradition with a vibrant energy inspired by ukiyo-e style. The composition combines symbolic creatures, movement and color in a scene full of life which celebrates the festival essence: the connection between Japanese culture, living together and celebrating.":"El nuevo cartel de 2026 reinterpreta la tradición japonesa con una energía vibrante inspirada en el estilo ukiyo-e. La composición combina criaturas simbólicas, movimiento y color en una escena llena de vida que celebra la esencia del festival: la conexión entre cultura japonesa, convivencia y celebración.",
      
      "Get official merchandise during the Matsuri or support our":"Consigue el merchandising oficial durante el Matsuri o colabora en nuestro",
      "crowdfunding":"crowdfunding",
      "campaign and receive exclusive gifts.":"para obtener regalos exclusivos.",

      "Information about the Event":"Información del Evento",
      "Know more":"saber más",
      "Matsuri BCN is a Japanese cultural festival here in Barcelona where people can come and enjoy live performance, authentic food and activities just like in Japan!":"Matsuri BCN es un festival cultural japonés aquí en Barcelona donde la gente puede venir y disfrutar de actuaciones en vivo, comida auténtica y actividades como en Japón.",
      "Matsuri Barcelona is an annual event where you can enjoy Japanese culture, with top artists and performances, numerous exhibitors, Japanese food and drink, a kid's area, and various activities typical of Japanese festivals, so you can enjoy an immersive and fun weekend with your family and friends.":"Matsuri Barcelona es un evento anual donde podrás disfrutar de la cultura japonesa, con los mejores artistas y actuaciones, numerosos expositores, comida y bebida japonesas, zona infantil y diversas actividades típicas de los festivales de Japón para que disfrutes de un fin de semana inmersivo y divertido junto a tu familia y amigos.",
      "Information":"Información",
      "PROGRAM":"PROGRAMA",
      "ARTISTS":"ARTISTAS",
      "KIDS AREA":"ZONA INFANTIL",
      "STANDS":"STANDS",
      "FOOD AND DRINKS":"COMIDA Y BEBIDA",
      "Location":"Ubicación",
      "Moll de la Fusta":"Moll de la Fusta",
      "Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona":"Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona",
      "Subway: Drassanes (L3) Barceloneta (L4)":"Metro: Drassanes (L3) Barceloneta (L4)",
      "Bus: 59, 120, D20, H14, V17":"Bus: 59, 120, D20, H14, V17",
      "Nearby parking available":"Aparcamiento cercano disponible",
      "Be part of Matsuri":"Sé parte de Matsuri",
      "Join our community as a volunteer or help us make one of Barcelona's biggest Japanese festivals happen through crowdfunding.":"Únete a nuestra comunidad como voluntario o ayúdanos a hacer uno de los festivales japoneses más grandes de Barcelona a través del crowdfunding.",
      "Become a volunteer":"Hazte voluntario",
      "Frequently asked questions":"Preguntas frecuentes",
      "Contact":"Contacto",
      "Cookie policy":"Política de cookies",
      "Privacy policy":"Política de privacidad",
      "Food and drink stalls": "Puestos de comida y bebida",
      "Crowdfund":"Crowdfunding",
      "Lang":"Idioma",
      "It will be announced in April":"Se anunciará en abril",
      "Call for applications expected in February":"Convocatoria prevista para febrero",
      "Start date set for February":"Inicio previsto para febrero",
      "Sponsors 2025":"patrocinadores 2025"
    },
    Català: {
      "Matsuri Barcelona Festival":"Festival Matsuri Barcelona",
      "MAY 16th and 17th - MOLL DE LA FUSTA":"16 i 17 DE MAIG - MOLL DE LA FUSTA",
      "Welcome": "Benvingut",
      "Buy your tickets now": "Compra les teves entrades ara",
      "TICKETS": "ENTRADES",
      "The Festival": "El Festival",
      "Activities": "Activitats",
      "Program": "Programa",
      "Artists": "Artistes",
      "Kids area": "Zona infantil",
      "Stands": "Stands",
      "Food and drinks": "Menjar i begudes",
      "About":"Referent a",
      "Support us":"Colabora",
      // "Support us":"Dóna'ns suport",
      "Contact":"Contacte",
      "Sponsor us":"Patrocina’ns",
      "Crowdfund us":"Crowdfunding",
      "Volunteering":"Voluntariat",
      "VALID TICKET SALES, ONLY THROUGH ENTRADIUM.COM":"VENDA D’ENTRADES VÀLIDES NOMÉS A TRAVÉS DE ENTRADIUM.COM",
      // -- ランタン --
      "Join the Matsuri":"Uneix-te al Matsuri",
      "We are opening the call for food vendors, exhibitors, and sponsors.": "Obrim la convocatòria per a restauració, expositors i patrocinadors.",
      "If you want to take part in the festival, fill out the corresponding form.": "Si vols participar en el festival, omple el formulari corresponent.",
      "Choose your profile and send us your proposal.": "Tria el teu perfil i envia’ns la teva proposta.",
      "Food Vendors":"Restauració",
      "Exhibitors": "Expositors",
      "Sponsors": "Patrocinadors",
      // -------------
      "Stands":"Stands",
      "Crowdfunding":"Crowdfunding",
      "Matsuri 2026 Poster":"Pòster Matsuri 2026",
      "We present our famous Matsuri Barcelona poster created every year by the tattoo artist": "Presentem el nostre famós cartell de Matsuri Barcelona creat cada any pel tatuador i artista",
      "Jun Chihara": "Jun Chihara",
      "The new 2026 poster reinterprets Japanese tradition with a vibrant energy inspired by ukiyo-e style. The composition combines symbolic creatures, movement and color in a scene full of life which celebrates the festival essence: the connection between Japanese culture, living together and celebrating.":"El nou cartell de 2026 reinterpreta la tradició japonesa amb una energia vibrant inspirada en l'estil ukiyo-e. La composició combina criatures simbòliques, moviment i color en una escena plena de vida que celebra l'essència del festival: la connexió entre cultura japonesa, convivència i celebració.",
      "Get official merchandise during the Matsuri or support our":"Aconsegueix el marxandatge oficial durant el Matsuri o col·labora amb el nostre",
      "crowdfunding":"crowdfunding",
      "campaign and receive exclusive gifts.":"i rep regals exclusius.",
      "Information about the Event":"Informació de l'esdeveniment",
      "Know more":"saber-ne més",
      "Matsuri BCN is a Japanese cultural festival here in Barcelona where people can come and enjoy live performance, authentic food and activities just like in Japan!":"Matsuri BCN és un festival cultural japonès aquí a Barcelona on la gent pot venir i gaudir d'actuacions en directe, menjar autèntic i activitats com al Japó!",
      "Matsuri Barcelona is an annual event where you can enjoy Japanese culture, with top artists and performances, numerous exhibitors, Japanese food and drink, a kid's area, and various activities typical of Japanese festivals, so you can enjoy an immersive and fun weekend with your family and friends.":"Matsuri Barcelona és un esdeveniment anual on podràs gaudir de la cultura japonesa, amb els millors artistes i actuacions, nombrosos expositors, menjar i beguda japonesos, zona infantil i diverses activitats típiques dels festivals del Japó perquè gaudeixis d’un cap de setmana immersiu i divertit amb la teva família i amics.",
      "Information":"Informació",
      "PROGRAM":"PROGRAMA",
      "ARTISTS":"ARTISTES",
      "KIDS AREA":"ZONA INFANTIL",
      "STANDS":"STANDS",
      "FOOD AND DRINKS":"MENJAR I BEGUDES",
      "Location":"Ubicació",
      "Moll de la Fusta":"Moll de la Fusta",
      "Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona":"Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona",
      "Subway: Drassanes (L3) Barceloneta (L4)":"Metro: Drassanes (L3) Barceloneta (L4)",
      "Bus: 59, 120, D20, H14, V17":"Bus: 59, 120, D20, H14, V17",
      "Nearby parking available":"Aparcament disponible a prop",
      "Be part of Matsuri":"Forma part de Matsuri",
      "Join our community as a volunteer or help us make one of Barcelona's biggest Japanese festivals happen through crowdfunding.":"Uneix-te a la nostra comunitat com a voluntari o ajuda'ns a fer un dels festivals japonesos més importants de Barcelona a través del crowdfunding.",
      "Become a volunteer":"Fes-te voluntari",
      "Frequently asked questions":"Preguntes freqüents",
      "Contact":"Contacte",
      "Cookie policy":"Política de cookies",
      "Privacy policy":"Política de privacitat",
      "Food and drink stalls": "Parades de menjar i beguda",
      "Crowdfund":"Crowdfunding",
      "Lang":"Llengua",
      "It will be announced in April":"S'anunciarà en abril",
      "Call for applications expected in February":"Convocatoria prevista per a febrer",
      "Start date set for February":"Inici previst per a febrer",
      "Sponsors 2025":"patrocinadors 2025"
    },
    日本語: {
      "Matsuri Barcelona Festival":"Matsuri Barcelona",
      "MAY 16th and 17th - MOLL DE LA FUSTA":"5月16日・17日 - MOLL DE LA FUSTA",
      "Welcome": "ようこそ",
      "Buy your tickets now": "チケットを購入する",
      "TICKETS": "チケット",
      "The Festival": "イベント情報",
      "Activities": "アクティビティ",
      "Program": "プログラム",
      "Artists": "出演者",
      "Kids area": "キッズエリア",
      "Stands":"ブース",
      "Food and drinks": "フード＆ドリンク",
      "About":"Matsuri BCNとは？",
      // "Support us":"応援する！",
      "Support us":"応援する",
      "Contact":"連絡先",
      "Sponsor us":"スポンサーになる",
      "Crowdfund us":"クラファンで応援！",
      "Volunteering":"ボランティア",
      "VALID TICKET SALES, ONLY THROUGH ENTRADIUM.COM":"有効なチケットはENTRADIUM.COMからのみ購入可能",
      // -- ランタン --
      "Join the Matsuri": "祭りに参加しよう",
      "We are opening the call for food vendors, exhibitors, and sponsors.": "飲食店、出展者、スポンサーの募集を開始しました。",
      "If you want to take part in the festival, fill out the corresponding form.": "フェスティバルに参加をご希望の方は、該当するフォームにご記入ください。",
      "Choose your profile and send us your proposal.": "プロフィールを選択し、企画案をお送りください。",
      "Food Vendors": "飲食出店",
      "Exhibitors": "出展者",
      "Sponsors": "スポンサー",
      // -------------
      "Stands":"スタンド",
      "Crowdfunding":"クラウドファンディング",
      "Matsuri 2026 Poster":"Matsuri Barcelonaの公式ポスターをご紹介します。",
      "We present our famous Matsuri Barcelona poster created every year by the tattoo artist": "Matsuri Barcelonaの公式ポスターをご紹介します。このポスターは、彫師でありアーティストでもあるJun Chiharaによって毎年制作されています。",
      "Jun Chihara": " ",
      "The new 2026 poster reinterprets Japanese tradition with a vibrant energy inspired by ukiyo-e style. The composition combines symbolic creatures, movement and color in a scene full of life which celebrates the festival essence: the connection between Japanese culture, living together and celebrating.":"2026年版の新しいポスターは、浮世絵のスタイルからインスピレーションを受けた躍動感あふれる表現で、日本の伝統を現代的に再解釈した作品です。象徴的な生き物たち、動きのある構図、そして鮮やかな色彩が組み合わさり、祭りの活気を感じさせる世界が描かれています。この作品は、Matsuri Barcelonaが大切にしている日本文化・人々の交流・祝祭の楽しさというエッセンスを表現しています。",
      "Get official merchandise during the Matsuri or support our":"イベント当日には、Matsuri公式グッズも販売予定です。また、",
      "crowdfunding":"クラウドファンディング",
      "campaign and receive exclusive gifts.":"に参加すると、限定グッズを手に入れることもできます。",
      "Information about the Event":"イベント情報",
      "Know more":"もっと知る",
      "Matsuri BCN is a Japanese cultural festival here in Barcelona where people can come and enjoy live performance, authentic food and activities just like in Japan!":"Matsuri BCN はバルセロナで開催される日本文化のお祭りで、本場日本のライブパフォーマンス、本格的な料理、アクティビティを楽しむことができます。",
      "Matsuri Barcelona is an annual event where you can enjoy Japanese culture, with top artists and performances, numerous exhibitors, Japanese food and drink, a kid's area, and various activities typical of Japanese festivals, so you can enjoy an immersive and fun weekend with your family and friends.":"Matsuri Barcelonaは、日本文化を楽しめる年に一度のイベントです。様々なアーティストやパフォーマンス、多数の出展者、日本の飲み物や食べ物、子ども向けエリアが準備され、日本の祭りならではのさまざまな体験型アクティビティが揃い、家族や友人と一緒に没入感あふれる楽しい週末をお楽しみいただけます！",
      "Information":"情報",
      "PROGRAM":"プログラム",
      "ARTISTS":"出演者",
      "KIDS AREA":"キッズエリア",
      "STANDS":"ブース",
      "FOOD AND DRINKS":"フード＆ドリンク",
      "Location":"開催場所",
      "Moll de la Fusta":"Moll de la Fusta",
      "Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona":"Moll de Bosch i Alsina, 1, Ciutat Vella, 08039 Barcelona",
      "Subway: Drassanes (L3) Barceloneta (L4)":"地下鉄: Drassanes (L3) Barceloneta (L4)",
      "Bus: 59, 120, D20, H14, V17":"バス: 59、120、D20、H4、V17",
      "Nearby parking available":"近くに駐車場あり",
      "Be part of Matsuri":"Matsuriを応援しませんか？",
      "Join our community as a volunteer or help us make one of Barcelona's biggest Japanese festivals happen through crowdfunding.":"当日のボランティアとしての参加、もしくはクラウドファンディングを通じてバルセロナ最大の日本フェスティバルの実現にご協力をお願いします！。",
      "Become a volunteer":"ボランティアになる",
      "Frequently asked questions":"よくある質問",
      "Contact":"連絡先",
      "Cookie policy":"クッキーポリシー",
      "Privacy policy":"プライバシーポリシー",
      "Food and drink stalls": "フード＆ドリンク屋台",
      "Crowdfund":"クラウドファンディング",
      "Lang":"言語",
      "It will be announced in April":"4月に発表予定",
      "Call for applications expected in February":"2月に公募を開始します",
      "Start date set for February":"2月に公募開始予定",
      "Sponsors 2025":"2025年開催時のスポンサー"
    }
};

const originalTextNodes = [];

const walker = document.createTreeWalker(
  document.body,
  NodeFilter.SHOW_TEXT,
  null
);

let node;
while ((node = walker.nextNode())) {
  const text = node.nodeValue.replace(/\s+/g, ' ').trim();
  if (text) {
    originalTextNodes.push({
      node,
      text
    });
  }
}

function translatePage(lang) {
  const dict = {
    ...(window.translations?.[lang] || {}),
    ...(translations?.[lang] || {})
  };

  originalTextNodes.forEach(({ node, text }) => {
    if (lang === 'English') {
      node.nodeValue = text;
      return;
    }
    if (dict[text]) {
      node.nodeValue = dict[text];
    }
  });
}
