window.translations = window.translations || {
    Español: {},
    Català: {},
    日本語: {}
};
Object.assign(window.translations.Español, {
    "About Matsuri BCN":"Acerca de Matsuri BCN",
    "Frequent Asked Questions":"Preguntas frecuentes",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.":"La Asociación de Cultura Japonesa Matsuri (マツリ日本文化協会) es una entidad sin ánimo de lucro con más de 13 años de recorrido en Barcelona. Desde que empezamos en 2013, trabajamos para acercar la cultura japonesa al público de forma abierta y accesible, pasando de una primera edición 1.500 personas a un festival consolidado que reunió a más de 40.000 asistentes en 2024.",
    "Buy your tickets":"Compra tus entradas",
    "HERE.":"AQUÍ.",
    "Learn more about what’s behind the event":"Conoce más sobre lo que hay detrás del evento",
    "HERE":"AQUÍ.",
    "This growth has been possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association's president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural dissemination. Our greatest asset is our people. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural and inclusive perspective, deeply connected to the cultural fabric of Barcelona.":"Este crecimiento ha sido posible gracias al compromiso del equipo, la implicación de la comunidad y una programación cultural diversa. En 2019, esta labor fue reconocida oficialmente cuando el presidente de la asociación recibió la Distinción del Cónsul General del Japón en Barcelona por su contribución a la difusión cultural. Nuestro principal valor es el capital humano. Contamos con más de 130 voluntarios de hasta 20 orígenes distintos, lo que nos permite trabajar desde una perspectiva intercultural, inclusiva y profundamente vinculada al tejido cultural de Barcelona.",
    "What are the event times?":"¿Cuál es el horario del evento?",
    "Matsuri will be open from 10am to 8pm, and the event will close at 9pm on both days.":"Se podrá acceder a Matsuri desde las 10h hasta las 20h, el evento se cerrará a las 21h ambos días.",
    "Do I need to buy tickets?":"¿Es necesario comprar entradas para asistir?",
    "Yes, Matsuri is a non-profit event created mostly by volunteers. Your contribution is very important for Matsuri to happen. You can buy your ticket at":"Sí, Matsuri es un evento sin ánimo de lucro creado mayormente por voluntarios, tu aportación es muy importante para poder hacer Matsuri. Puedes comprar tu entrada en",
    "There are discounts for early bird purchases!":"¡Hay descuentos por compra anticipada!",
    "Admission is free for those born on or after January 1, 2014, and for people with disabilities and one companion. An official disability certificate can be requested (an official resolution will be accepted even with a disability rating below 33%).":"La entrada es gratuita para los nacidos a partir del 1 de enero de 2014 (inclusive) y para personas con discapacidad y un acompañante. Se podrá solicitar certificado oficial (se aceptará resolución oficial incluso con grado inferior al 33%).",
    "Can I go inside in and out Matsuri as I please?":"¿Puedo salir y volver a entrar al recinto?",
    "No, due to safety and capacity regulations, leaving and re-entering are not permitted. We recommend you come and spend the day, as there are all sorts of activities you'll love, as well as a food court.":"No, por normas de seguridad y aforo no se permite salir y volver a entrar. Te recomendamos que vengas a pasar el día, ya que hay todo tipo de actividades que te encantarán y también zona de restauración.",
    "Can I access it with my scooter or bicycle?":"¿Puedo acceder con mi patinete o bicicleta?",
    "Access with scooters, bicycles or other vehicles is not allowed.":"No se permite el acceso con patinetes, bicicletas u otros vehículos.",
    "Can I bring food or drinks?":"¿Puedo acceder con comida o bebida?",
    "According to Barcelona's Municipal Ordinance, bringing food and drinks from outside (including cans and glass) is prohibited.":"De acuerdo con la Ordenanza Municipal de Barcelona, está prohibido introducir comida y bebida del exterior (incluidas latas y envases de vidrio).",
    "Exception:":"Excepción:",
    "only":"se permite únicamente el acceso con",
    "WATER":"AGUA",
    "is permitted (to prevent heatstroke).":"(por prevención de golpes de calor).",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"(Sostenibilidad: Recomendamos el uso de botellas reutilizables para reducir el plástico).",
    "Can I bring my dog?":"¿Puedo ir con mi perro?",
    "Yes, dogs are part of the family too, but they must be kept on a leash, and please help us keep the grounds clean by picking up after them. Please be aware that there are many people and noises at Matsuri that might frighten them.":"Sí, los perros también son parte de la familia, pero deben ir atados con correa y, por favor, ayúdanos a mantener el recinto limpio haciéndote cargo de sus deposiciones. Ten en cuenta que en Matsuri hay mucha gente y ruidos que le pueden asustar.",
    "Is it necessary to register for the workshops in advance?":"¿Es necesario inscribirse previamente en los talleres?",
    "Some workshops require prior registration. We'll help you at the Information stand located at the entrance.":"Algunos talleres requieren inscribirse previamente. En el stand de Información que encontrarás en la entrada te ayudaremos.",
    "Is there vegetarian or vegan food?":"¿Hay comida vegetariana o vegana?",
    "Yes, there are options for everyone.":"Sí, hay opciones para todos.",
    "How can I participate as a volunteer?":"¿Cómo puedo participar como voluntario?",
    "Please,":"Por favor,", 
    "fill out this form":"rellena este formulario",
    "and we will contact you as soon as possible":"y nos pondremos en contacto contigo lo antes posible",
    "How can I collaborate as a sponsor?":"¿Cómo puedo colaborar como patrocinador?",
    "In this section you will find all the information":"En esta sección encontrarás toda la información",
    "and the email address where you can apply to become a sponsor.":"y el correo donde aplicar para ser patrocinador.",
    "How can I participate as an artist or cultural group?":"¿Cómo puedo participar como artista o grupo cultural?",
    "Please send us an email at":"Por favor, envíanos un correo a",
    "colaboracion@acjm.es":"colaboracion@acjm.es",
    "and we will get back to you as soon as possible.":"y te responderemos lo antes posible.",
    "How can I participate with a food stall?":"¿Cómo puedo participar en la zona de restauración?",
    "Is there a children’s area?":"¿Hay zona para los niños?",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age, but they must always be accompanied by an adult.":"Matsuri cuenta con una zona especial para niños, donde podrán disfrutar de actividades adaptadas a su edad, pero deben ir siempre acompañados de un adulto.",
    "Very soon you will be able to check the children’s program in this section.":"Muy pronto podrás consultar el programa infantil en esta sección.",
});
Object.assign(window.translations.Català, {
    "About Matsuri BCN":"Sobre Matsuri BCN",
    "Frequent Asked Questions":"Preguntes freqüents",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.":"L’Associació de Cultura Japonesa Matsuri (マツリ日本文化協会) és una entitat sense ànim de lucre amb més de 13 anys d’experiència a Barcelona. Des que vam començar el 2013, treballem per acostar la cultura japonesa al públic de manera oberta i accessible, passant de 1.500 persones a la primera edició a un festival consolidat que va reunir més de 40.000 assistents el 2024.",
    "Buy your tickets":"Compra les teves entrades",
    "HERE.":"AQUÍ.",
    "Learn more about what’s behind the event":"Coneix més sobre el que hi ha darrere de l’esdeveniment",
    "HERE":"AQUÍ.",
    "This growth has been possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association's president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural dissemination. Our greatest asset is our people. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural and inclusive perspective, deeply connected to the cultural fabric of Barcelona.":"Aquest creixement ha estat possible gràcies al compromís de l’equip, la implicació de la comunitat i una programació cultural diversa. El 2019, aquesta tasca va ser reconeguda oficialment quan el president de l’associació va rebre la Distinció del Consol General del Japó a Barcelona per la seva contribució a la difusió cultural. El nostre principal valor és el capital humà. Comptem amb més de 130 voluntaris procedents de fins a 20 orígens diferents, cosa que ens permet treballar des d’una perspectiva intercultural, inclusiva i profundament vinculada al teixit cultural de Barcelona.",
    "What are the event times?":"Quin és l’horari de l’esdeveniment?",
    "Matsuri will be open from 10am to 8pm, and the event will close at 9pm on both days.":"Es podrà accedir al Matsuri de les 10 h fins a les 20 h. L’esdeveniment es tancarà a les 21 h els dos dies.",
    "Do I need to buy tickets?":"Cal comprar entrada per assistir-hi?",
    "Yes, Matsuri is a non-profit event created mostly by volunteers. Your contribution is very important for Matsuri to happen. You can buy your ticket at":"Sí. Matsuri és un esdeveniment sense ànim de lucre creat majoritàriament per voluntaris, i la teva aportació és molt important per poder fer possible el Matsuri. Pots comprar la teva entrada a",
    "There are discounts for early bird purchases!":"Hi ha descomptes per compra anticipada!",
    "Admission is free for those born on or after January 1, 2014, and for people with disabilities and one companion. An official disability certificate can be requested (an official resolution will be accepted even with a disability rating below 33%).":"L’entrada és gratuïta per a les persones nascudes a partir de l’1 de gener de 2014 (inclòs) i per a persones amb discapacitat i un acompanyant. Es podrà sol·licitar certificat oficial (s’acceptarà resolució oficial fins i tot amb un grau inferior al 33%).",
    "Can I go inside in and out Matsuri as I please?":"Puc sortir i tornar a entrar al recinte?",
    "No, due to safety and capacity regulations, leaving and re-entering are not permitted. We recommend you come and spend the day, as there are all sorts of activities you'll love, as well as a food court.":"No. Per motius de seguretat i aforament no està permès sortir i tornar a entrar. Et recomanem venir a passar el dia sencer, ja que hi ha moltes activitats que t’encantaran i també zona de restauració.",
    "Can I access it with my scooter or bicycle?":"Puc accedir amb el meu patinet o bicicleta?",
    "Access with scooters, bicycles or other vehicles is not allowed.":"No es permet l’accés amb patinets, bicicletes ni altres vehicles.",
    "Can I bring food or drinks?":"Puc accedir amb menjar o beguda?",
    "According to Barcelona's Municipal Ordinance, bringing food and drinks from outside (including cans and glass) is prohibited.":"D’acord amb l’Ordenança Municipal de Barcelona, està prohibit introduir menjar i begudes de l’exterior (incloses llaunes i envasos de vidre).",
    "Exception:":"Excepció:",
    "only":"només es permet l’accés amb",
    "WATER":"AIGUA",
    "is permitted (to prevent heatstroke).":"(per prevenir cops de calor).",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"(Sostenibilitat: Recomanem l’ús d’ampolles reutilitzables per reduir el plàstic).",
    "Can I bring my dog?":"Puc anar amb el meu gos?",
    "Yes, dogs are part of the family too, but they must be kept on a leash, and please help us keep the grounds clean by picking up after them. Please be aware that there are many people and noises at Matsuri that might frighten them.":"Sí, els gossos també són part de la família, però han d’anar lligats amb corretja. Si us plau, ajuda’ns a mantenir el recinte net fent-te càrrec de les seves deposicions. Tingues en compte que a Matsuri hi ha molta gent i sorolls que el poden espantar.",
    "Is it necessary to register for the workshops in advance?":"Cal inscriure’s prèviament als tallers?",
    "Some workshops require prior registration. We'll help you at the Information stand located at the entrance.":"Alguns tallers requereixen inscripció prèvia. Al punt d’Informació que trobaràs a l’entrada t’ajudarem.",
    "Is there vegetarian or vegan food?":"Hi ha menjar vegetarià o vegà?",
    "Yes, there are options for everyone.":"Sí, hi ha opcions per a tothom.",
    "How can I participate as a volunteer?":"Com puc participar com a voluntari/ària?",
    "Please,":"Si us plau,", 
    "fill out this form":"omple aquest formulari",
    "and we will contact you as soon as possible":"i ens posarem en contacte amb tu tan aviat com sigui possible",
    "How can I collaborate as a sponsor?":"Com puc col·laborar com a patrocinador?",
    "In this section you will find all the information":"En aquesta secció trobaràs tota la informació",
    "and the email address where you can apply to become a sponsor.":"i el correu on sol·licitar ser patrocinador.",
    "How can I participate as an artist or cultural group?":"Com puc participar com a artista o grup cultural?",
    "Please send us an email at":"Si us plau, envia’ns un correu a",
    "colaboracion@acjm.es":"colaboracion@acjm.es",
    "and we will get back to you as soon as possible.":"i et respondrem al més aviat possible.",
    "How can I participate with a food stall?":"Com puc participar a la zona de restauració?",
    "Is there a children’s area?":"Hi ha una zona per a nens?",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age, but they must always be accompanied by an adult.":"Matsuri compta amb una zona especial per a infants, on podran gaudir d’activitats adaptades a la seva edat, però sempre han d’anar acompanyats d’un adult.",
    "Very soon you will be able to check the children’s program in this section.":"Molt aviat podràs consultar el programa infantil en aquesta secció.",
});
Object.assign(window.translations.日本語, {
    "About Matsuri BCN":"Matsuri BCNについて",
    "Frequent Asked Questions":"よくある質問",
    "The Matsuri Japanese Culture Association (マツリ日本文化協会) is a non-profit organization with over 13 years of experience in Barcelona. Since we started in 2013, we have worked to bring Japanese culture closer to the public in an open and accessible way, growing from 1,500 attendees at the first edition to a well-established festival that attracted over 40,000 visitors in 2024.": "マツリ日本文化協会（Matsuri Japanese Culture Association）は、バルセロナで13年以上の歴史を持つ非営利団体です。2013年の設立以来、私たちは日本文化を広く誰でも楽しめる形で紹介することに取り組んできました。初回の来場者1,500人から、2024年には4万人以上を動員する確立されたフェスティバルへと成長しました。",
    "Buy your tickets":"チケットは",
    "HERE.":"こちらで購入してください。",
    "Learn more about what’s behind the event":"イベントの裏側について詳しくは",
    "HERE":"こちらでご覧ください。",
    "This growth has been possible thanks to the commitment of our team, the involvement of the community, and a diverse cultural program. In 2019, this work was officially recognized when the association's president received the Distinction from the Consul General of Japan in Barcelona for his contribution to cultural dissemination. Our greatest asset is our people. We have more than 130 volunteers from up to 20 different backgrounds, which allows us to work from an intercultural and inclusive perspective, deeply connected to the cultural fabric of Barcelona.": "この成長は、チームの献身、コミュニティの関与、多様な文化プログラムのおかげで実現しました。2019年には、この活動が正式に評価され、協会の代表がバルセロナ日本国総領事より文化普及への貢献として表彰を受けました。私たちの最大の資産は人材です。20以上の異なるバックグラウンドを持つ130人以上のボランティアがおり、これによりバルセロナの文化的ネットワークと深く結びつきながら、異文化的で包括的な視点から活動することが可能になっています。",
    "What are the event times?":"イベントの開催時間は何時ですか？",
    "Matsuri will be open from 10am to 8pm, and the event will close at 9pm on both days.":"祭りは10時から20時まで入場可能です。両日ともイベントは21時に終了します。",
    "Do I need to buy tickets?":"参加するにはチケットの購入が必要ですか？",
    "Yes, Matsuri is a non-profit event created mostly by volunteers. Your contribution is very important for Matsuri to happen. You can buy your ticket at":"はい。祭りは主にボランティアによって運営されている非営利イベントであり、皆さまのご協力が祭りの開催にとって非常に重要です。チケットは以下のリンクから購入できます。",
    "There are discounts for early bird purchases!":"前売り割引があります！",
    "Admission is free for those born on or after January 1, 2014, and for people with disabilities and one companion. An official disability certificate can be requested (an official resolution will be accepted even with a disability rating below 33%).":"2014年1月1日以降（同日含む）に生まれた方、および障がいのある方とその付き添いの方1名は入場無料です。公式証明書の提示をお願いする場合があります（障がい等級が33％未満の場合でも、公式な認定書があれば受け付けます）。",
    "Can I go inside in and out Matsuri as I please?":"会場から一度出て、再入場することはできますか？",
    "No, due to safety and capacity regulations, leaving and re-entering are not permitted. We recommend you come and spend the day, as there are all sorts of activities you'll love, as well as a food court.":"いいえ。安全および収容人数の都合上、再入場はできません。ぜひ一日を通してお楽しみください。魅力的なアクティビティや飲食エリアもご用意しています。",
    "Can I access it with my scooter or bicycle?":"キックボードや自転車で入場できますか？",
    "Access with scooters, bicycles or other vehicles is not allowed.":"キックボード、自転車、その他の乗り物での入場はできません。",
    "Can I bring food or drinks?":"食べ物や飲み物を持ち込むことはできますか？",
    "According to Barcelona's Municipal Ordinance, bringing food and drinks from outside (including cans and glass) is prohibited.":"バルセロナ市の市条例により、外部からの飲食物（缶およびガラス容器を含む）の持ち込みは禁止されています。",
    "Exception:":"例外:",
    "only":"熱中症予防のため、",
    "WATER":"水のみ",
    "is permitted (to prevent heatstroke).":"持ち込み可能です",
    "(Sustainability: We recommend using reusable bottles to reduce plastic waste.)":"（サステナビリティ：プラスチック削減のため、再利用可能なボトルの使用を推奨しています。）",
    "Can I bring my dog?":"犬を連れて行ってもいいですか？",
    "Yes, dogs are part of the family too, but they must be kept on a leash, and please help us keep the grounds clean by picking up after them. Please be aware that there are many people and noises at Matsuri that might frighten them.":"はい、犬も家族の一員ですが、必ずリードを着用してください。また、排泄物の処理にご協力いただき、会場を清潔に保つようお願いいたします。Matsuriは人が多く、音も大きいため、犬が怖がる場合がありますのでご注意ください。",
    "Is it necessary to register for the workshops in advance?":"ワークショップに事前登録は必要ですか？",
    "Some workshops require prior registration. We'll help you at the Information stand located at the entrance.":"一部のワークショップでは事前登録が必要です。入口にあるインフォメーションブースでスタッフがご案内します。",
    "Is there vegetarian or vegan food?":"ベジタリアンやヴィーガン向けの食事はありますか？",
    "Yes, there are options for everyone.":"はい、どなたにもお楽しみいただける選択肢があります。",
    "How can I participate as a volunteer?":"ボランティアとして参加するにはどうすればいいですか？",
    "Please,":"恐れ入りますが", 
    "fill out this form":"こちらのフォームにご記入ください",
    "and we will contact you as soon as possible":"できるだけ早くご連絡いたします",
    "How can I collaborate as a sponsor?":"スポンサーとして協力するにはどうすればいいですか？",
    "In this section you will find all the information":"このセクションでは",
    "and the email address where you can apply to become a sponsor.":"、スポンサーになるために応募するためのすべての情報と連絡先メールをご確認いただけます。",
    "How can I participate as an artist or cultural group?":"アーティストや文化グループとして参加するにはどうすればいいですか？",
    "Please send us an email at":"恐れ入りますが、",
    "colaboracion@acjm.es":"colaboracion@acjm.es",
    "and we will get back to you as soon as possible.":"までメールをお送りください。できるだけ早くご返信いたします。",
    "How can I participate with a food stall?":"飲食エリアに参加するにはどうすればいいですか？",
    "Is there a children’s area?":"子ども用エリアはありますか？",
    "Matsuri has a special area for children, where they can enjoy activities adapted to their age, but they must always be accompanied by an adult.":"Matsuri には子ども向けの特別エリアがあり、年齢に合わせたアクティビティを楽しむことができますが、必ず大人の同伴が必要です。",
    "Very soon you will be able to check the children’s program in this section.":"このセクションでは、まもなく子ども向けプログラムをご確認いただけます。",
});